function result = vi_cylinder_wnl_adjoint_schur_solve( ...
        blocks,omega,spec,direct,userOpts)
%VI_CYLINDER_WNL_ADJOINT_SCHUR_SOLVE Low-rank temporal adjoint null solve.
%
% The cylinder forcing matrices have nonzero entries only in a small set of
% interface-displacement columns. Eliminating each uncoupled temporal block
% gives S*zeta=0. Equal-order primitive collocation can leave pressure-only
% right/left nullspaces in every D_j. A minimum-norm SVD border removes only
% those algebraic directions before forming S; no physical equation is
% shifted. A left nullvector of S then reconstructs the full adjoint. The
% caller still checks the complete, unmodified equation A'*y=0.

if nargin < 5
    userOpts = struct();
end
opts = wnl_options(userOpts);
validateattributes(opts.adjointCylinderSchurUseNullspaceBordering, ...
    {'logical','numeric'},{'scalar'});
validateattributes(opts.adjointCylinderSchurNullTolerance,{'numeric'}, ...
    {'scalar','real','positive','finite'});
validateattributes(opts.adjointCylinderSchurMaximumNullity,{'numeric'}, ...
    {'scalar','integer','positive','finite'});
validateattributes(opts.adjointCylinderSchurBlockRefinementSteps, ...
    {'numeric'},{'scalar','integer','nonnegative','finite'});
validateattributes(opts.adjointCylinderSchurFactorResidualTolerance, ...
    {'numeric'},{'scalar','real','positive','finite'});
numberOfHarmonics = numel(spec.n);
ndof = size(blocks.B0,1);
direct = direct(:);
if numel(direct) ~= ndof*numberOfHarmonics
    error('vi_cylinder_wnl_adjoint_schur_solve:DirectSize', ...
        'The direct vector has the wrong number of entries.');
end

previousCoupling = -blocks.Lplus;
nextCoupling = -blocks.Lminus;
activeColumns = active_coupling_columns( ...
    previousCoupling,nextCoupling);
numberOfActiveColumns = numel(activeColumns);
information = initial_information(numberOfHarmonics, ...
    numberOfActiveColumns);
result = struct('vector',complex(zeros(size(direct))), ...
    'diagnostics',information);
if numberOfActiveColumns == 0
    result.diagnostics.stopReason = ...
        'the temporal forcing has no active interface columns';
    return;
end

solverClock = tic;
try
    factors = cell(numberOfHarmonics,1);
    diagonals = cell(numberOfHarmonics,1);
    previousResponse = cell(numberOfHarmonics,1);
    nextResponse = cell(numberOfHarmonics,1);
    maximumResponseResidual = 0;
    maximumOriginalResponseResidual = 0;
    blockNullity = zeros(numberOfHarmonics,1);
    blockFactorMethods = cell(numberOfHarmonics,1);
    [~,referenceIndex] = min(abs(spec.n(:)+spec.s));
    referenceDiagonal = temporal_diagonal( ...
        blocks,omega,spec,referenceIndex);
    borderBasis = pressure_nullspace_border( ...
        referenceDiagonal,blocks.B0,opts);
    information.borderReferenceHarmonic = spec.n(referenceIndex);
    information.borderNullity = borderBasis.nullity;
    information.borderRightNullResidual = ...
        borderBasis.rightNullResidual;
    information.borderRightMassResidual = ...
        borderBasis.rightMassResidual;
    factorClock = tic;
    warningState = suppress_factor_warnings();
    cleanup = onCleanup(@() restore_warning_states(warningState));
    for harmonicIndex = 1:numberOfHarmonics
        diagonal = temporal_diagonal( ...
            blocks,omega,spec,harmonicIndex);
        diagonals{harmonicIndex} = diagonal;
        factors{harmonicIndex} = factor_temporal_system( ...
            diagonal,borderBasis,harmonicIndex);
        blockNullity(harmonicIndex) = ...
            factors{harmonicIndex}.nullity;
        blockFactorMethods{harmonicIndex} = ...
            factors{harmonicIndex}.method;
        rightHandSide = [ ...
            previousCoupling(:,activeColumns), ...
            nextCoupling(:,activeColumns)];
        [response,~,augmentedResidual] = refined_factor_solve( ...
            factors{harmonicIndex},rightHandSide, ...
            opts.adjointCylinderSchurBlockRefinementSteps,false);
        if any(~isfinite(real(response(:)))) || ...
                any(~isfinite(imag(response(:))))
            error('vi_cylinder_wnl_adjoint_schur_solve:NonfiniteFactor', ...
                'Temporal block %d returned a nonfinite response.', ...
                harmonicIndex);
        end
        previousResponse{harmonicIndex} = ...
            response(:,1:numberOfActiveColumns);
        nextResponse{harmonicIndex} = ...
            response(:,numberOfActiveColumns+1:end);
        responseResidual = norm(augmentedResidual,'fro') / ...
            max(norm(rightHandSide,'fro'),eps);
        originalResponseResidual = norm( ...
            diagonal*response-rightHandSide,'fro') / ...
            max(norm(rightHandSide,'fro'),eps);
        maximumResponseResidual = max( ...
            maximumResponseResidual,responseResidual);
        maximumOriginalResponseResidual = max( ...
            maximumOriginalResponseResidual,originalResponseResidual);
    end
    information.factorSeconds = toc(factorClock);
    information.maximumResponseResidual = maximumResponseResidual;
    information.maximumOriginalResponseResidual = ...
        maximumOriginalResponseResidual;
    information.blockNullityRange = finite_range(blockNullity);
    information.blockFactorMethods = unique(blockFactorMethods,'stable');

    reduced = assemble_reduced_system( ...
        spec,activeColumns,previousResponse,nextResponse);
    [leftVectors,singularValues] = svd(full(reduced),'econ');
    singularValues = diag(singularValues);
    [minimumSingularValue,minimumIndex] = min(singularValues);
    reducedLeft = leftVectors(:,minimumIndex);
    information.reducedDimension = size(reduced,1);
    information.reducedMinimumSingularValue = minimumSingularValue;
    information.reducedRelativeSingularValue = ...
        minimumSingularValue/max(max(singularValues),eps);
    information.reducedLeftResidual = ...
        norm(reduced'*reducedLeft)/max(norm(reducedLeft),eps);

    leftByHarmonic = complex(zeros(ndof,numberOfHarmonics));
    maximumReconstructionResidual = 0;
    maximumOriginalReconstructionResidual = 0;
    maximumBorderMultiplierRatio = 0;
    for harmonicIndex = 1:numberOfHarmonics
        reducedIndices = local_reduced_indices( ...
            harmonicIndex,numberOfActiveColumns);
        rightHandSide = complex(zeros(ndof,1));
        rightHandSide(activeColumns) = reducedLeft(reducedIndices);
        [leftByHarmonic(:,harmonicIndex),borderMultiplier, ...
            augmentedResidual] = refined_factor_solve( ...
            factors{harmonicIndex},rightHandSide, ...
            opts.adjointCylinderSchurBlockRefinementSteps,true);
        reconstructionResidual = norm(augmentedResidual) / ...
            max(norm(rightHandSide),eps);
        originalReconstructionResidual = norm( ...
            diagonals{harmonicIndex}'* ...
            leftByHarmonic(:,harmonicIndex)-rightHandSide) / ...
            max(norm(rightHandSide),eps);
        borderMultiplierRatio = norm(borderMultiplier) / ...
            max(norm(leftByHarmonic(:,harmonicIndex)),eps);
        maximumReconstructionResidual = max( ...
            maximumReconstructionResidual,reconstructionResidual);
        maximumOriginalReconstructionResidual = max( ...
            maximumOriginalReconstructionResidual, ...
            originalReconstructionResidual);
        maximumBorderMultiplierRatio = max( ...
            maximumBorderMultiplierRatio,borderMultiplierRatio);
    end
    clear cleanup;
    information.maximumReconstructionResidual = ...
        maximumReconstructionResidual;
    information.maximumOriginalReconstructionResidual = ...
        maximumOriginalReconstructionResidual;
    information.maximumBorderMultiplierRatio = ...
        maximumBorderMultiplierRatio;
    left = leftByHarmonic(:);
    residual = complete_adjoint_residual( ...
        blocks,omega,spec,leftByHarmonic);
    information.absoluteResidual = norm(residual(:));
    information.residualPerLeftNorm = ...
        information.absoluteResidual/max(norm(left),eps);
    factorGate = maximumResponseResidual <= ...
        opts.adjointCylinderSchurFactorResidualTolerance && ...
        maximumReconstructionResidual <= ...
        opts.adjointCylinderSchurFactorResidualTolerance;
    information.passedFactorGate = factorGate;
    information.available = all(isfinite(real(left))) && ...
        all(isfinite(imag(left))) && factorGate;
    information.totalSeconds = toc(solverClock);
    if information.available
        information.stopReason = [ ...
            'pressure-nullspace-bordered temporal Schur adjoint ', ...
            'reconstructed'];
    else
        information.stopReason = ...
            'the temporal Schur adjoint missed its factor residual gate';
    end
    result.vector = left;
    result.diagnostics = information;
    if opts.verbose
        fprintf(['WNL cylinder adjoint Schur solve (%s): reduced %d, ', ...
            'relative sigma %.3e, nullity [%g,%g], augmented ', ...
            'response/reconstruction residual %.3e/%.3e, original ', ...
            'adjoint residual/left norm %.3e, %.3f s.\n'],spec.label, ...
            information.reducedDimension, ...
            information.reducedRelativeSingularValue, ...
            information.blockNullityRange(1), ...
            information.blockNullityRange(2), ...
            information.maximumResponseResidual, ...
            information.maximumReconstructionResidual, ...
            information.residualPerLeftNorm, ...
            information.totalSeconds);
    end
catch solverError
    information.errorIdentifier = solverError.identifier;
    information.errorMessage = solverError.message;
    information.stopReason = sprintf( ...
        'cylinder adjoint Schur solve unavailable: %s', ...
        solverError.message);
    information.totalSeconds = toc(solverClock);
    result.diagnostics = information;
end
end

function information = initial_information(numberOfHarmonics,activeColumns)
information = struct('attempted',true,'available',false, ...
    'method','cylinder low-rank temporal Schur adjoint', ...
    'numberOfHarmonics',numberOfHarmonics, ...
    'numberOfActiveColumns',activeColumns,'reducedDimension',0, ...
    'reducedMinimumSingularValue',NaN, ...
    'reducedRelativeSingularValue',NaN,'reducedLeftResidual',Inf, ...
    'maximumResponseResidual',Inf, ...
    'maximumOriginalResponseResidual',Inf, ...
    'maximumReconstructionResidual',Inf, ...
    'maximumOriginalReconstructionResidual',Inf, ...
    'maximumBorderMultiplierRatio',Inf, ...
    'blockNullityRange',[NaN,NaN],'blockFactorMethods',{{}}, ...
    'borderReferenceHarmonic',NaN,'borderNullity',0, ...
    'borderRightNullResidual',Inf,'borderRightMassResidual',Inf, ...
    'passedFactorGate',false, ...
    'absoluteResidual',Inf,'residualPerLeftNorm',Inf, ...
    'factorSeconds',0,'totalSeconds',0,'stopReason','not attempted', ...
    'errorIdentifier','','errorMessage','');
end

function columns = active_coupling_columns(previousCoupling,nextCoupling)
[~,previousColumns] = find(previousCoupling);
[~,nextColumns] = find(nextCoupling);
columns = unique([previousColumns;nextColumns]);
columns = columns(:).';
end

function diagonal = temporal_diagonal(blocks,omega,spec,harmonicIndex)
frequency = spec.n(harmonicIndex)+spec.s;
diagonal = (wnl_spec_lambda(spec)+1i*omega*frequency)*blocks.B0 - ...
    blocks.L0;
end

function reduced = assemble_reduced_system( ...
        spec,activeColumns,previousResponse,nextResponse)
numberOfHarmonics = numel(spec.n);
numberOfActiveColumns = numel(activeColumns);
reduced = speye(numberOfActiveColumns*numberOfHarmonics);
for harmonicIndex = 1:numberOfHarmonics
    rowIndices = local_reduced_indices( ...
        harmonicIndex,numberOfActiveColumns);
    previousPosition = find( ...
        spec.n == spec.n(harmonicIndex)-1,1);
    nextPosition = find(spec.n == spec.n(harmonicIndex)+1,1);
    if ~isempty(previousPosition)
        columnIndices = local_reduced_indices( ...
            previousPosition,numberOfActiveColumns);
        reduced(rowIndices,columnIndices) = ...
            reduced(rowIndices,columnIndices) + ...
            previousResponse{harmonicIndex}(activeColumns,:);
    end
    if ~isempty(nextPosition)
        columnIndices = local_reduced_indices( ...
            nextPosition,numberOfActiveColumns);
        reduced(rowIndices,columnIndices) = ...
            reduced(rowIndices,columnIndices) + ...
            nextResponse{harmonicIndex}(activeColumns,:);
    end
end
end

function residual = complete_adjoint_residual( ...
        blocks,omega,spec,left)
numberOfHarmonics = numel(spec.n);
residual = complex(zeros(size(left)));
previousCoupling = -blocks.Lplus;
nextCoupling = -blocks.Lminus;
for harmonicIndex = 1:numberOfHarmonics
    value = temporal_diagonal( ...
        blocks,omega,spec,harmonicIndex)'*left(:,harmonicIndex);
    previousPosition = find( ...
        spec.n == spec.n(harmonicIndex)-1,1);
    nextPosition = find(spec.n == spec.n(harmonicIndex)+1,1);
    if ~isempty(previousPosition)
        value = value+nextCoupling'*left(:,previousPosition);
    end
    if ~isempty(nextPosition)
        value = value+previousCoupling'*left(:,nextPosition);
    end
    residual(:,harmonicIndex) = value;
end
end

function basis = pressure_nullspace_border(matrix,mass,opts)
matrixSize = size(matrix,1);
leftNull = complex(zeros(matrixSize,0));
rightNull = complex(zeros(matrixSize,0));
nullity = 0;
if opts.adjointCylinderSchurUseNullspaceBordering
    numberRequested = min( ...
        opts.adjointCylinderSchurMaximumNullity,matrixSize-1);
    [leftVectors,singularValues,rightVectors] = ...
        svds(matrix,numberRequested,'smallest');
    [singularValues,order] = sort(real(diag(singularValues)),'ascend');
    leftVectors = leftVectors(:,order);
    rightVectors = rightVectors(:,order);
    threshold = opts.adjointCylinderSchurNullTolerance* ...
        max(norm(matrix,1),1);
    nullity = sum(singularValues <= threshold);
    if nullity == numberRequested && ...
            numberRequested < matrixSize-1
        error(['vi_cylinder_wnl_adjoint_schur_solve:', ...
            'TemporalNullspaceLimit'], ...
            ['At least %d null vectors were detected in the reference ', ...
             'temporal block; increase ', ...
             'adjointCylinderSchurMaximumNullity.'],numberRequested);
    end
    leftNull = leftVectors(:,1:nullity);
    rightNull = rightVectors(:,1:nullity);
    if nullity > 0
        massColumnNorm = full(sqrt(sum(abs(mass).^2,1))).';
        algebraicColumns = massColumnNorm <= ...
            max(max(massColumnNorm)*1.0e-13,eps);
        projectedRight = complex(zeros(size(rightNull)));
        projectedRight(algebraicColumns,:) = ...
            rightNull(algebraicColumns,:);
        [projectedRight,~] = qr(projectedRight,0);
        projectedResidual = norm(matrix*projectedRight,'fro') / ...
            max(norm(matrix,1)*norm(projectedRight,'fro'),eps);
        rawResidual = norm(matrix*rightNull,'fro') / ...
            max(norm(matrix,1)*norm(rightNull,'fro'),eps);
        if projectedResidual <= max( ...
                100*rawResidual,10*opts.adjointCylinderSchurNullTolerance)
            rightNull = projectedRight;
        end
    end
end
basis = struct('left',leftNull,'right',rightNull,'nullity',nullity, ...
    'rightNullResidual',norm(matrix*rightNull,'fro') / ...
    max(norm(matrix,1)*max(norm(rightNull,'fro'),1),eps), ...
    'rightMassResidual',norm(mass*rightNull,'fro') / ...
    max(norm(mass,1)*max(norm(rightNull,'fro'),1),eps));
end

function factor = factor_temporal_system(matrix,basis,harmonicIndex)
matrixSize = size(matrix,1);
nullity = basis.nullity;
if nullity > 0
    rightResidual = norm(matrix*basis.right,'fro') / ...
        max(norm(matrix,1)*norm(basis.right,'fro'),eps);
    if ~isfinite(rightResidual) || rightResidual > 1.0e-9
        error(['vi_cylinder_wnl_adjoint_schur_solve:', ...
            'NoninvariantPressureNullspace'], ...
            ['The reference pressure nullspace is not invariant in ', ...
             'temporal block %d (relative residual %.3e).'], ...
            harmonicIndex,rightResidual);
    end
    augmented = [matrix,sparse(basis.left); ...
        sparse(basis.right'),sparse(nullity,nullity)];
    method = 'pressure-nullspace-bordered-lu';
else
    augmented = matrix;
    method = 'equilibrated-lu';
end
augmentedSize = size(augmented,1);
rowNorm = full(sqrt(sum(abs(augmented).^2,2)));
rowScale = 1./max(rowNorm,eps);
rowScaled = spdiags(rowScale,0,augmentedSize,augmentedSize)*augmented;
columnNorm = full(sqrt(sum(abs(rowScaled).^2,1))).';
columnScale = 1./max(columnNorm,eps);
scaled = rowScaled*spdiags( ...
    columnScale,0,augmentedSize,augmentedSize);
factor = struct('matrix',augmented,'rowScale',rowScale, ...
    'columnScale',columnScale,'decomposition', ...
    decomposition(scaled,'lu'),'numberOfStateRows',matrixSize, ...
    'nullity',nullity,'method',method);
end

function [solution,borderMultiplier,residual] = refined_factor_solve( ...
        factor,rightHandSide,steps,transposeSolve)
augmentedRightHandSide = [rightHandSide;complex(zeros( ...
    factor.nullity,size(rightHandSide,2)))];
augmentedSolution = scaled_factor_solve( ...
    factor,augmentedRightHandSide,transposeSolve);
for refinementStep = 1:steps
    if transposeSolve
        residual = augmentedRightHandSide- ...
            factor.matrix'*augmentedSolution;
    else
        residual = augmentedRightHandSide- ...
            factor.matrix*augmentedSolution;
    end
    oldNorm = norm(residual,'fro');
    if oldNorm <= 64*eps*max(norm(augmentedRightHandSide,'fro'),1)
        break;
    end
    correction = scaled_factor_solve(factor,residual,transposeSolve);
    if any(~isfinite(real(correction(:)))) || ...
            any(~isfinite(imag(correction(:))))
        break;
    end
    trial = augmentedSolution+correction;
    if transposeSolve
        newNorm = norm( ...
            augmentedRightHandSide-factor.matrix'*trial,'fro');
    else
        newNorm = norm( ...
            augmentedRightHandSide-factor.matrix*trial,'fro');
    end
    if ~isfinite(newNorm) || newNorm >= oldNorm*(1-64*eps)
        break;
    end
    augmentedSolution = trial;
end
if transposeSolve
    residual = factor.matrix'*augmentedSolution-augmentedRightHandSide;
else
    residual = factor.matrix*augmentedSolution-augmentedRightHandSide;
end
solution = augmentedSolution(1:factor.numberOfStateRows,:);
borderMultiplier = augmentedSolution( ...
    factor.numberOfStateRows+1:end,:);
end

function solution = scaled_factor_solve( ...
        factor,rightHandSide,transposeSolve)
if transposeSolve
    solution = factor.rowScale.* ...
        (factor.decomposition'\(factor.columnScale.*rightHandSide));
else
    solution = factor.columnScale.* ...
        (factor.decomposition\(factor.rowScale.*rightHandSide));
end
end

function indices = local_reduced_indices(position,blockSize)
indices = (position-1)*blockSize+(1:blockSize);
end

function range = finite_range(values)
values = values(isfinite(values));
if isempty(values)
    range = [NaN,NaN];
else
    range = [min(values),max(values)];
end
end

function states = suppress_factor_warnings()
warningIds = {'MATLAB:singularMatrix','MATLAB:nearlySingularMatrix'};
states = repmat(struct('identifier','','state',''),numel(warningIds),1);
for warningIndex = 1:numel(warningIds)
    states(warningIndex) = warning('off',warningIds{warningIndex});
end
end

function restore_warning_states(states)
for warningIndex = 1:numel(states)
    warning(states(warningIndex).state,states(warningIndex).identifier);
end
end
