function [input, summary] = vi_wnl_apply_runtime_profile(input)
%VI_WNL_APPLY_RUNTIME_PROFILE Apply transparent WNL cost/accuracy presets.
%
% Profiles cap expensive truncation and first-pass iteration settings. They
% never increase a user-supplied resolution. If automatic eigenpair
% continuation is enabled, a nearly converged first pass may use the
% separate escalation limits without rebuilding the grid or repeating the
% prescribed-interface lift. 'final' leaves numerical resolution untouched.

if ~isfield(input,'execution') || ~isfield(input.execution,'profile')
    input.execution.profile = 'balanced';
end
if ~(ischar(input.execution.profile) || ...
        (isstring(input.execution.profile) && ...
        isscalar(input.execution.profile)))
    error('vi_wnl_apply_runtime_profile:ProfileType', ...
        ['input.execution.profile must be a character vector or scalar ', ...
         'string: ''development'', ''balanced'', or ''final''. A logical ', ...
         'value usually means that forcedUseBlockGmres was assigned to ', ...
         'the wrong field.']);
end
profile = lower(char(input.execution.profile));
if ~isfield(input.execution,'nonlinearTemporalOversampling')
    input.execution.nonlinearTemporalOversampling = 2.0;
end
if ~isfield(input.execution,'adaptiveDirectionalSteps')
    input.execution.adaptiveDirectionalSteps = true;
end
if ~isfield(input.execution,'quadraticStepMultipliers')
    input.execution.quadraticStepMultipliers = [1,2,4,8];
end
if ~isfield(input.execution,'cubicStepMultipliers')
    input.execution.cubicStepMultipliers = [1,2,4];
end
if ~isfield(input.options,'autoEscalateEigenpairRefinement')
    input.options.autoEscalateEigenpairRefinement = true;
end
defaultWnlOptions = wnl_options();
if ~isfield(input.options,'eigenpairCorrectionRegularization')
    input.options.eigenpairCorrectionRegularization = ...
        defaultWnlOptions.eigenpairCorrectionRegularization;
end
if ~isfield(input.options,'eigenpairCorrectionEquationTolerance')
    input.options.eigenpairCorrectionEquationTolerance = ...
        defaultWnlOptions.eigenpairCorrectionEquationTolerance;
end
completionFields = { ...
    'eigenpairUseAlgebraicCompletion', ...
    'eigenpairAlgebraicCompletionRegularization', ...
    'eigenpairAlgebraicCompletionSolveTolerance', ...
    'eigenpairAlgebraicCompletionEquationTolerance', ...
    'eigenpairAlgebraicCompletionMaxIterations', ...
    'eigenpairAlgebraicCompletionMaxRestarts'};
for fieldIndex = 1:numel(completionFields)
    fieldName = completionFields{fieldIndex};
    if ~isfield(input.options,fieldName)
        input.options.(fieldName) = defaultWnlOptions.(fieldName);
    end
end
forcedCompletionFields = { ...
    'forcedSolveResidualTolerance', ...
    'forcedUseAlgebraicCompletion', ...
    'forcedAlgebraicCompletionRegularization', ...
    'forcedAlgebraicCompletionSolveTolerance', ...
    'forcedAlgebraicCompletionEquationTolerance', ...
    'forcedAlgebraicCompletionMaxIterations', ...
    'forcedAlgebraicCompletionMaxRestarts', ...
    'forcedAlgebraicCompletionMaximumResidualGrowth', ...
    'forcedAlgebraicCompletionMaximumFullNormRatio', ...
    'forcedCorrectionRegularization', ...
    'forcedLineSearchMaxCuts', ...
    'forcedFailFast', ...
    'forcedUseRankAwareMinimumNorm', ...
    'forcedRankToleranceFactors', ...
    'forcedTryDefaultRankTolerance', ...
    'forcedColumnEquilibrationFloorRatio', ...
    'forcedUseCylinderSchur', ...
    'forcedCylinderSchurBlockRefinementSteps', ...
    'forcedCylinderSchurReducedRefinementSteps', ...
    'forcedCylinderSchurBlockRegularization', ...
    'forcedCylinderSchurBlockRegularizationGrowth', ...
    'forcedCylinderSchurBlockRegularizationAttempts', ...
    'forcedCylinderSchurBlockMaximumInverseGain', ...
    'forcedUseBlockGmres', ...
    'forcedGmresRestart', ...
    'forcedGmresMaxCycles', ...
    'forcedGmresStagnationCycles', ...
    'forcedGmresMinimumCycleImprovement', ...
    'forcedBlockRegularization', ...
    'forcedBlockRegularizationGrowth', ...
    'forcedBlockRegularizationAttempts', ...
    'forcedBlockMaximumInverseGain'};
for fieldIndex = 1:numel(forcedCompletionFields)
    fieldName = forcedCompletionFields{fieldIndex};
    if ~isfield(input.options,fieldName)
        input.options.(fieldName) = defaultWnlOptions.(fieldName);
    end
end
if ~ismember(profile,{'development','balanced','final'})
    error('vi_wnl_apply_runtime_profile:UnknownProfile', ...
        'execution.profile must be development, balanced, or final.');
end

requestedN = input.numerics.N;
requestedNr = input.numerics.Nr;
requestedNtheta = input.numerics.Ntheta;
switch profile
    case 'development'
        input.execution.nonlinearTemporalOversampling = min( ...
            input.execution.nonlinearTemporalOversampling,1.0);
        input.numerics.N = min(input.numerics.N,5);
        input.numerics.Nr = min(input.numerics.Nr,9);
        input.numerics.Ntheta = min(input.numerics.Ntheta,24);
        if strcmpi(input.numerics.verticalGrid.type,'multidomain') && ...
                isempty(input.numerics.verticalGrid.lowerBreaks) && ...
                isempty(input.numerics.verticalGrid.upperBreaks)
            input.numerics.verticalGrid.pointsPerBoundaryLayer = min( ...
                input.numerics.verticalGrid.pointsPerBoundaryLayer,7);
            input.numerics.verticalGrid.pointsInBulk = min( ...
                input.numerics.verticalGrid.pointsInBulk,9);
        end
        input.options.directLiftMaxRestarts = min( ...
            input.options.directLiftMaxRestarts,1);
        input.options.modeTrackingMaxIterations = min( ...
            input.options.modeTrackingMaxIterations,5000);
        input.options.eigenpairRefinementMaxSteps = min( ...
            input.options.eigenpairRefinementMaxSteps,3);
        input.options.eigenpairGmresMaxCycles = min( ...
            input.options.eigenpairGmresMaxCycles,8);
        input.options.eigenpairLsqrFallbackMaxIterations = min( ...
            input.options.eigenpairLsqrFallbackMaxIterations,0);
        input.options.eigenpairAlgebraicCompletionMaxIterations = min( ...
            input.options.eigenpairAlgebraicCompletionMaxIterations,0);
        input.options.forcedSolveMaxIterations = min( ...
            input.options.forcedSolveMaxIterations,3000);
        input.options.forcedSolveMaxRestarts = min( ...
            input.options.forcedSolveMaxRestarts,0);
        input.options.forcedGmresMaxCycles = min( ...
            input.options.forcedGmresMaxCycles,8);
        input.options.forcedAlgebraicCompletionMaxIterations = min( ...
            input.options.forcedAlgebraicCompletionMaxIterations,0);
    case 'balanced'
        input.execution.nonlinearTemporalOversampling = min( ...
            input.execution.nonlinearTemporalOversampling,1.5);
        input.numerics.N = min(input.numerics.N,7);
        input.numerics.Nr = min(input.numerics.Nr,12);
        input.numerics.Ntheta = min(input.numerics.Ntheta,32);
        if strcmpi(input.numerics.verticalGrid.type,'multidomain') && ...
                isempty(input.numerics.verticalGrid.lowerBreaks) && ...
                isempty(input.numerics.verticalGrid.upperBreaks)
            input.numerics.verticalGrid.pointsPerBoundaryLayer = min( ...
                input.numerics.verticalGrid.pointsPerBoundaryLayer,9);
            input.numerics.verticalGrid.pointsInBulk = min( ...
                input.numerics.verticalGrid.pointsInBulk,11);
        end
        input.options.directLiftMaxRestarts = min( ...
            input.options.directLiftMaxRestarts,3);
        input.options.modeTrackingMaxIterations = min( ...
            input.options.modeTrackingMaxIterations,10000);
        input.options.eigenpairRefinementMaxSteps = min( ...
            input.options.eigenpairRefinementMaxSteps,5);
        input.options.eigenpairGmresMaxCycles = min( ...
            input.options.eigenpairGmresMaxCycles,15);
        input.options.eigenpairLsqrFallbackMaxIterations = min( ...
            input.options.eigenpairLsqrFallbackMaxIterations,750);
        input.options.eigenpairAlgebraicCompletionMaxIterations = min( ...
            input.options.eigenpairAlgebraicCompletionMaxIterations,500);
        input.options.eigenpairAlgebraicCompletionMaxRestarts = min( ...
            input.options.eigenpairAlgebraicCompletionMaxRestarts,0);
        input.options.forcedSolveMaxIterations = min( ...
            input.options.forcedSolveMaxIterations,7500);
        input.options.forcedSolveMaxRestarts = min( ...
            input.options.forcedSolveMaxRestarts,2);
        input.options.forcedGmresMaxCycles = min( ...
            input.options.forcedGmresMaxCycles,30);
        input.options.forcedAlgebraicCompletionMaxIterations = min( ...
            input.options.forcedAlgebraicCompletionMaxIterations,500);
        input.options.forcedAlgebraicCompletionMaxRestarts = min( ...
            input.options.forcedAlgebraicCompletionMaxRestarts,0);
end

summary = struct();
summary.profile = profile;
summary.requestedN = requestedN;
summary.requestedNr = requestedNr;
summary.requestedNtheta = requestedNtheta;
summary.appliedN = input.numerics.N;
summary.appliedNr = input.numerics.Nr;
summary.appliedNtheta = input.numerics.Ntheta;
summary.forcedUseBlockGmres = input.options.forcedUseBlockGmres;
summary.forcedUseRankAwareMinimumNorm = ...
    input.options.forcedUseRankAwareMinimumNorm;
summary.forcedUseCylinderSchur = input.options.forcedUseCylinderSchur;
summary.forcedCylinderSchurBlockRegularization = ...
    input.options.forcedCylinderSchurBlockRegularization;
summary.forcedCylinderSchurBlockRegularizationAttempts = ...
    input.options.forcedCylinderSchurBlockRegularizationAttempts;
summary.forcedRankToleranceFactors = ...
    input.options.forcedRankToleranceFactors;
summary.forcedGmresMaxCycles = input.options.forcedGmresMaxCycles;
summary.nonlinearTemporalOversampling = ...
    input.execution.nonlinearTemporalOversampling;
summary.adaptiveDirectionalSteps = ...
    input.execution.adaptiveDirectionalSteps;
summary.quadraticStepMultipliers = ...
    input.execution.quadraticStepMultipliers;
summary.cubicStepMultipliers = ...
    input.execution.cubicStepMultipliers;
summary.autoEscalateEigenpairRefinement = ...
    input.options.autoEscalateEigenpairRefinement;
summary.eigenpairGmresMaxCycles = ...
    input.options.eigenpairGmresMaxCycles;
summary.eigenpairLsqrFallbackMaxIterations = ...
    input.options.eigenpairLsqrFallbackMaxIterations;
summary.eigenpairCorrectionRegularization = ...
    input.options.eigenpairCorrectionRegularization;
summary.eigenpairCorrectionEquationTolerance = ...
    input.options.eigenpairCorrectionEquationTolerance;
summary.eigenpairUseAlgebraicCompletion = ...
    input.options.eigenpairUseAlgebraicCompletion;
summary.eigenpairAlgebraicCompletionMaxIterations = ...
    input.options.eigenpairAlgebraicCompletionMaxIterations;
summary.forcedUseAlgebraicCompletion = ...
    input.options.forcedUseAlgebraicCompletion;
summary.forcedAlgebraicCompletionMaxIterations = ...
    input.options.forcedAlgebraicCompletionMaxIterations;
summary.forcedCorrectionRegularization = ...
    input.options.forcedCorrectionRegularization;
summary.forcedFailFast = input.options.forcedFailFast;
summary.isFinal = strcmp(profile,'final');
fprintf(['Runtime profile %-11s: N=%d, Nr=%d, Ntheta=%d, temporal ', ...
    'oversampling=%.3g, forced block-GMRES=%d\n'],profile, ...
    input.numerics.N,input.numerics.Nr,input.numerics.Ntheta, ...
    input.execution.nonlinearTemporalOversampling, ...
    input.options.forcedUseBlockGmres);
fprintf(['  Direct eigenpair correction: physical GMRES probe <= %d ', ...
    'cycle(s); LSQR fallback <= %d iteration(s).\n'], ...
    input.options.eigenpairGmresMaxCycles, ...
    input.options.eigenpairLsqrFallbackMaxIterations);
fprintf(['  LSQR physical regularization %.1e; accepted correction ', ...
    'equation residual <= %.1e.\n'], ...
    input.options.eigenpairCorrectionRegularization, ...
    input.options.eigenpairCorrectionEquationTolerance);
fprintf(['  DAE algebraic completion enabled=%d, <= %d LSQR ', ...
    'iteration(s) for a pressure-inflated physical trial.\n'], ...
    input.options.eigenpairUseAlgebraicCompletion, ...
    input.options.eigenpairAlgebraicCompletionMaxIterations);
fprintf(['  Forced-field DAE completion enabled=%d, <= %d LSQR ', ...
    'iteration(s); correction regularization %.1e; fail-fast=%d.\n'], ...
    input.options.forcedUseAlgebraicCompletion, ...
    input.options.forcedAlgebraicCompletionMaxIterations, ...
    input.options.forcedCorrectionRegularization, ...
    input.options.forcedFailFast);
fprintf(['  Forced temporal-block GMRES enabled=%d, <= %d cycle(s); ', ...
    'physical residual gate remains %.1e.\n'], ...
    input.options.forcedUseBlockGmres, ...
    input.options.forcedGmresMaxCycles, ...
    input.options.forcedSolveResidualTolerance);
fprintf(['  Rank-aware minimum norm enabled=%d; rank factors %s; ', ...
    'physical residual is always checked before coefficients.\n'], ...
    input.options.forcedUseRankAwareMinimumNorm, ...
    mat2str(input.options.forcedRankToleranceFactors));
fprintf(['  Cylinder low-rank temporal Schur solve enabled=%d; ', ...
    'block/reduced refinement steps %d/%d; fallback shift %.1e ', ...
    'for %d attempt(s).\n'], ...
    input.options.forcedUseCylinderSchur, ...
    input.options.forcedCylinderSchurBlockRefinementSteps, ...
    input.options.forcedCylinderSchurReducedRefinementSteps, ...
    input.options.forcedCylinderSchurBlockRegularization, ...
    input.options.forcedCylinderSchurBlockRegularizationAttempts);
fprintf(['  Adaptive ALE directional steps enabled=%d; quadratic %s; ', ...
    'cubic %s.\n'],input.execution.adaptiveDirectionalSteps, ...
    mat2str(input.execution.quadraticStepMultipliers), ...
    mat2str(input.execution.cubicStepMultipliers));
if ~summary.isFinal
    fprintf(['  Preliminary profile: repeat accepted coefficients with ', ...
        'execution.profile=''final'' and perform a grid/truncation study.\n']);
end
if summary.autoEscalateEigenpairRefinement
    fprintf(['  Adaptive eigenpair continuation is enabled: a ', ...
        'near-converged first pass may use the escalation limits.\n']);
end
end
