function diagnostic = wnl_assert_reference_eigenvalue_consistent( ...
        mode,userOpts)
%WNL_ASSERT_REFERENCE_EIGENVALUE_CONSISTENT Gate WNL on model agreement.

if nargin < 2
    userOpts = struct();
end
opts = wnl_options(userOpts);
diagnostic = wnl_reference_eigenvalue_consistency(mode,opts);
if opts.enforceReducedFullEigenvalueAgreement && ...
        diagnostic.applicable && ~diagnostic.consistent
    error('wnl_assert_reference_eigenvalue_consistent:MismatchTooLarge', ...
        ['Mode %s has converged to a full-state exponent that does not ', ...
         'agree with its reduced operating-point seed: reduced ', ...
         'lambda %.6g%+.6gi, full lambda %.6g%+.6gi, absolute shift ', ...
         '%.3e, relative shift %.3e, allowed shift %.3e. Nonlinear ', ...
         'coefficients were not evaluated. Increase N/Nr/Nz until the ', ...
         'reduced and full linear modes agree; do not bypass this by ', ...
         'relaxing the algebraic residual tolerance.'],mode.spec.label, ...
        real(diagnostic.initialLambda),imag(diagnostic.initialLambda), ...
        real(diagnostic.finalLambda),imag(diagnostic.finalLambda), ...
        diagnostic.absoluteMismatch,diagnostic.relativeMismatch, ...
        diagnostic.allowedMismatch);
end
end
