function wnl_assert_mode_converged(mode, opts)
%WNL_ASSERT_MODE_CONVERGED Gate nonlinear coefficients on linear accuracy.

validateattributes(opts.modeResidualTolerance, {'numeric'}, ...
    {'scalar', 'real', 'positive', 'finite'});
checkDirect = get_check(opts,'checkDirectModeResidual',true);
checkAdjoint = get_check(opts,'checkAdjointModeResidual',true);
if ~checkDirect && ~checkAdjoint
    error('wnl_assert_mode_converged:NoSelectedResidual', ...
        'At least one mode-residual component must be selected.');
end
if (checkDirect && ~isfinite(mode.directResidual)) || ...
        (checkAdjoint && ~isfinite(mode.leftResidual))
    error('wnl_assert_mode_converged:NonfiniteResidual', ...
        ['Mode %s has a nonfinite selected residual: direct %.3e ', ...
         '(checked=%d), adjoint %.3e (checked=%d). Nonlinear ', ...
         'coefficients cannot be evaluated. Inspect the direct and ', ...
         'bordered-adjoint solver diagnostics.'], ...
        mode.spec.label,mode.directResidual,checkDirect, ...
        mode.leftResidual,checkAdjoint);
end
if ~opts.stopOnUnconvergedMode
    return;
end
selectedResiduals = [];
if checkDirect
    selectedResiduals(end+1) = mode.directResidual; %#ok<AGROW>
end
if checkAdjoint
    selectedResiduals(end+1) = mode.leftResidual; %#ok<AGROW>
end
largestResidual = max(selectedResiduals);
if largestResidual > opts.modeResidualTolerance
    error('wnl_assert_mode_converged:ResidualTooLarge', ...
        ['Floquet mode %s is not sufficiently converged: direct ', ...
         'residual %.3e (checked=%d), adjoint residual %.3e ', ...
         '(checked=%d), required tolerance %.3e. Nonlinear ', ...
         'coefficients were not evaluated. Refine N/Nr/Nz, verify that ', ...
         'the reduced and full operating-point eigenpairs agree, and ', ...
         'require ', ...
         'the mode-reconstruction iterative solves to converge.'], ...
        mode.spec.label, mode.directResidual,checkDirect, ...
        mode.leftResidual,checkAdjoint,opts.modeResidualTolerance);
end
end

function value = get_check(opts,name,defaultValue)
value = defaultValue;
if isfield(opts,name)
    value = opts.(name);
end
if ~(islogical(value) && isscalar(value)) && ...
        ~(isnumeric(value) && isscalar(value) && isfinite(value) && ...
          ismember(value,[0,1]))
    error('wnl_assert_mode_converged:BadComponentSelection', ...
        'opts.%s must be a logical scalar.',name);
end
value = logical(value);
end
