function [projected, diagnostics] = wnl_project_self_conjugate_field( ...
        model,field,userOpts)
%WNL_PROJECT_SELF_CONJUGATE_FIELD Remove anti-real numerical contamination.
%
% A forced field in an axisymmetric harmonic or subharmonic block has no
% arbitrary phase: real forcing selects the fixed point of physical
% conjugation. Averaging with that conjugate removes only numerical
% contamination. The measured defect is retained as an acceptance gate.

if nargin < 3
    userOpts = struct();
end
opts = wnl_options(userOpts);
if ~strcmp(wnl_mode_coordinate_type(field.spec, ...
        opts.realModeEigenvalueTolerance, ...
        opts.realModeMinimumConjugateOverlap),'real')
    error('wnl_project_self_conjugate_field:NotSelfConjugate', ...
        'Field %s is not in a self-conjugate real Floquet block.', ...
        field.spec.label);
end

reflected = wnl_conjugate_field(model,field, ...
    [field.spec.label,'_reality_projection']);
if ~wnl_equivalent_spec(field.spec,reflected.spec)
    error('wnl_project_self_conjugate_field:BlockMismatch', ...
        'Physical conjugation changed the requested Floquet block.');
end
originalVector = wnl_field_vector(field);
reflectedVector = wnl_field_vector(reflected);
relativeDefect = norm(originalVector-reflectedVector) / ...
    max(norm(originalVector),eps);
projectedVector = 0.5*(originalVector+reflectedVector);
projected = wnl_make_field(field.spec,projectedVector);
projectedReflection = wnl_conjugate_field(model,projected, ...
    [field.spec.label,'_projected_check']);
projectedResidual = norm(projectedVector- ...
    wnl_field_vector(projectedReflection))/max(norm(projectedVector),eps);

diagnostics = struct('relativeDefect',relativeDefect, ...
    'relativeProjectionChange', ...
    norm(projectedVector-originalVector)/max(norm(originalVector),eps), ...
    'projectedRealityResidual',projectedResidual, ...
    'tolerance',opts.realFieldConjugacyTolerance, ...
    'accepted',isfinite(relativeDefect) && ...
    relativeDefect <= opts.realFieldConjugacyTolerance);
end
