function mode = wnl_compute_mode(model, spec, userOpts)
%WNL_COMPUTE_MODE Compute and normalize a direct/left Floquet null pair.
%
% Required model callback:
%   block = model.block(spec)
%
% Required block fields:
%   block.A      complete square Floquet matrix
%   block.Bslow  descriptor matrix multiplying the physical slow derivative
%
% The algebraic left vector y satisfies y'*A=0 and is normalized so that
% y'*Bslow*phi=1. It already contains any discrete adjoint weights needed
% for solvability; use y'*forcing for projections.

if nargin < 3
    userOpts = struct();
end
opts = wnl_options(userOpts);
modeWallClock = tic;
directWallClock = tic;
block = model.block(spec);
validate_block(block, spec);
tracking = struct();
tracking.used = false;
tracking.recoveryCacheUsed = isfield(spec,'recoveryCacheFile') && ...
    ~isempty(spec.recoveryCacheFile);
if tracking.recoveryCacheUsed
    tracking.recoveryCacheFile = spec.recoveryCacheFile;
else
    tracking.recoveryCacheFile = '';
end
directSingularValue = NaN;
leftSingularValue = NaN;

if ~isempty(opts.direct)
    direct = opts.direct(:);
elseif isfield(spec, 'direct') && ~isempty(spec.direct)
    direct = spec.direct(:);
elseif isfield(spec, 'directSeed') && ~isempty(spec.directSeed)
    if isfield(spec, 'prescribedDofs') && ...
            ~isempty(spec.prescribedDofs)
        [direct, directSingularValue, tracking.direct] = ...
            reconstruct_from_prescribed_dofs(block, ...
            spec.directSeed(:), spec, opts);
    else
        [direct, directSingularValue, tracking.direct] = ...
            tracked_constrained_null(block, ...
            spec.directSeed(:), opts);
    end
    tracking.used = true;
    if opts.verbose
        fprintf(['WNL direct reconstruction (%s, %s): effective sigma ', ...
            '= %.3e, scaled residual = %.3e, selected attempt = ', ...
            '%d/%d, LSQR flag = %d, total iterations = %d, ', ...
            'restarts = %d\n'], ...
            spec.label, tracking.direct.method, ...
            directSingularValue, ...
            tracking.direct.scaledResidual, ...
            tracking.direct.selectedAttempt, ...
            tracking.direct.numberOfAttempts, ...
            tracking.direct.flag, ...
            tracking.direct.iterations, tracking.direct.restarts);
    end
else
    [~, directSingularValue, direct] = smallest_svd(block.A, opts);
    if opts.verbose
        fprintf('WNL direct null solve (%s): sigma_min = %.3e\n', ...
            spec.label, directSingularValue);
    end
end
directSolveSeconds = toc(directWallClock);

if numel(direct) ~= size(block.A, 2)
    error('wnl_compute_mode:DirectSize', ...
        'Direct vector has %d entries; block requires %d.', ...
        numel(direct), size(block.A, 2));
end

if ~isempty(opts.normalizeDirect)
    trialField = wnl_make_field(spec, direct);
    normalized = opts.normalizeDirect(trialField);
    if isstruct(normalized)
        direct = wnl_field_vector(normalized);
    else
        direct = normalized(:);
    end
end

% The reduced interface Schur complement and the full primitive-variable
% discretization need not have exactly the same Floquet exponent.  At an
% operating point, refine both the full state and lambda before constructing
% the adjoint or nonlinear forcing.  Holding every interface coefficient
% fixed leaves an O(1e-6) residual floor that can be strongly amplified by
% the second-order light-fluid Stokes solve.
tracking.eigenpairRefinement = struct('attempted',false);
eigenpairRefinementSeconds = 0;
if tracking.used && opts.refineOperatingPointEigenpair && ...
        abs(wnl_spec_lambda(spec)) > 1.0e-13
    validateattributes(opts.coefficientModeResidualTolerance,{'numeric'}, ...
        {'scalar','real','positive','finite'});
    validateattributes( ...
        opts.eigenpairEscalationMaximumResidualRatio,{'numeric'}, ...
        {'scalar','real','>=',1,'finite'});
    validateattributes(opts.eigenpairEscalationMaxSteps,{'numeric'}, ...
        {'scalar','integer','positive'});
    eigenpairWallClock = tic;
    firstPassOpts = opts;
    if opts.autoEscalateEigenpairRefinement
        firstPassOpts.eigenpairRefinementMaxSteps = min( ...
            opts.eigenpairRefinementMaxSteps, ...
            opts.eigenpairEscalationMaxSteps);
    end
    [spec, block, direct, firstRefinement] = ...
        refine_operating_point_eigenpair(model,spec,block,direct, ...
        firstPassOpts);
    firstRefinement.escalated = false;
    firstRefinement.numberOfPasses = 1;
    firstRefinement.directResidualReady = ...
        firstRefinement.finalResidual <= ...
        opts.coefficientModeResidualTolerance;
    tracking.eigenpairRefinement = firstRefinement;
    remainingEscalationSteps = max(0, ...
        opts.eigenpairEscalationMaxSteps-firstRefinement.steps);
    if opts.autoEscalateEigenpairRefinement && ...
            ~firstRefinement.directResidualReady && ...
            ~firstRefinement.stoppedForReferenceMismatch && ...
            strcmp(firstRefinement.stopReason, ...
                'Newton-step budget exhausted') && ...
            remainingEscalationSteps > 0 && ...
            firstRefinement.finalResidual < ...
                firstRefinement.initialResidual && ...
            firstRefinement.finalResidual <= ...
                opts.eigenpairEscalationMaximumResidualRatio * ...
                opts.coefficientModeResidualTolerance
        escalationOpts = opts;
        escalationOpts.eigenpairRefinementMaxSteps = ...
            remainingEscalationSteps;
        escalationOpts.eigenpairReferenceLambda = ...
            firstRefinement.initialLambda;
        escalationOpts.eigenpairPriorAcceptedSteps = ...
            firstRefinement.steps;
        if opts.verbose
            fprintf(['WNL automatic eigenpair continuation (%s): ', ...
                'first-pass residual %.3e; continuing from the best ', ...
                'state with %d remaining Newton step(s) in the total ', ...
                '%d-step budget.\n'], ...
                spec.label,firstRefinement.finalResidual, ...
                remainingEscalationSteps, ...
                opts.eigenpairEscalationMaxSteps);
        end
        [spec,block,direct,escalationRefinement] = ...
            refine_operating_point_eigenpair(model,spec,block,direct, ...
            escalationOpts);
        tracking.eigenpairRefinement = combine_refinement_passes( ...
            firstRefinement,escalationRefinement,opts);
    end
    if ~isempty(opts.normalizeDirect)
        normalized = opts.normalizeDirect(wnl_make_field(spec,direct));
        if isstruct(normalized)
            direct = wnl_field_vector(normalized);
        else
            direct = normalized(:);
        end
    end
    if opts.verbose
        refinement = tracking.eigenpairRefinement;
        fprintf(['WNL full eigenpair refinement (%s): lambda shift ', ...
            '= %.6g%+.6gi, scaled residual %.3e -> %.3e, ', ...
            'Newton steps = %d in %d pass(es), eigen-tolerance ', ...
            'converged = %d, direct coefficient-residual ready = %d\n'], ...
            spec.label, ...
            real(refinement.lambdaShift),imag(refinement.lambdaShift), ...
            refinement.initialResidual,refinement.finalResidual, ...
            refinement.steps,refinement.numberOfPasses, ...
            refinement.converged,refinement.directResidualReady);
        fprintf('  eigenpair refinement stop reason: %s\n', ...
            refinement.stopReason);
        if isfield(refinement,'phaseConstraintSource')
            fprintf('  eigenpair phase/scale anchor: %s\n', ...
                refinement.phaseConstraintSource);
        end
    end
    eigenpairRefinementSeconds = toc(eigenpairWallClock);
end

adjointWallClock = tic;
if ~isempty(opts.left)
    left = opts.left(:);
elseif isfield(spec, 'left') && ~isempty(spec.left)
    left = spec.left(:);
elseif tracking.used
    % Solve the exactly normalized bordered adjoint equations
    %
    %   A'*left + directUnit*alpha = 0,
    %   (Bslow*directUnit)'*left = 1.
    %
    % Multiplication of the first row by the direct null vector forces the
    % border multiplier alpha to zero at exact neutrality.  Unlike the
    % earlier penalty-constrained least-squares solve, this formulation
    % removes the null direction without introducing a large artificial
    % constraint weight.  It is substantially better conditioned for the
    % primitive velocity-pressure descriptor matrix.
    [left, leftSingularValue, tracking.left] = ...
        bordered_adjoint_null(block.A, block.Bslow, direct, spec, opts);
    if opts.verbose
        fprintf(['WNL bordered adjoint solve (%s): effective sigma = ', ...
            '%.3e, scaled residual = %.3e, method = %s, flag = %d, ', ...
            'iterations = %d, restarts = %d, constraint residual = ', ...
            '%.3e, valid = %d\n'], ...
            spec.label, leftSingularValue, ...
            tracking.left.scaledResidual, tracking.left.solver, ...
            tracking.left.flag, ...
            tracking.left.iterations, tracking.left.restarts, ...
            tracking.left.constraintResidual, ...
            tracking.left.candidateValid);
    end
else
    [~, leftSingularValue, left] = smallest_svd(block.A', opts);
end
adjointSeconds = toc(adjointWallClock);

if numel(left) ~= size(block.A, 1)
    error('wnl_compute_mode:LeftSize', ...
        'Left vector has %d entries; block requires %d.', ...
        numel(left), size(block.A, 1));
end

normalization = left' * (block.Bslow * direct);
if ~isfinite(real(normalization)) || ~isfinite(imag(normalization))
    error('wnl_compute_mode:NonfiniteNormalization', ...
        ['The adjoint reconstruction produced a nonfinite descriptor ', ...
         'pairing. Inspect the bordered-solver flag, normalization-row ', ...
         'residual, and temporal-block regularization diagnostics.']);
end
if abs(normalization) < opts.nullTolerance * norm(left) * ...
        max(norm(block.Bslow * direct), eps)
    error('wnl_compute_mode:ZeroNormalization', ...
        ['The direct/left pair has a nearly zero descriptor pairing. ', ...
         'The selected null vectors may belong to different modes.']);
end
left = left / conj(normalization);

[directResidual,directResidualDetails] = wnl_descriptor_residual( ...
    block.A,block.Bslow,direct,'direct');
[leftResidual,leftResidualDetails] = wnl_descriptor_residual( ...
    block.A,block.Bslow,left,'adjoint');

mode = struct();
mode.spec = spec;
mode.block = block;
mode.vector = direct;
mode.field = wnl_make_field(spec, direct);
mode.left = left;
mode.leftField = wnl_make_field(spec, left);
mode.normalization = left' * (block.Bslow * direct);
mode.directResidual = directResidual;
mode.leftResidual = leftResidual;
mode.directResidualDetails = directResidualDetails;
mode.leftResidualDetails = leftResidualDetails;
mode.directSingularValue = directSingularValue;
mode.leftSingularValue = leftSingularValue;
mode.tracking = tracking;
mode.timing = struct('directSolveSeconds',directSolveSeconds, ...
    'eigenpairRefinementSeconds',eigenpairRefinementSeconds, ...
    'adjointSeconds',adjointSeconds,'totalSeconds',toc(modeWallClock));

if opts.verbose
    fprintf(['WNL mode %s: direct residual %.3e, left residual %.3e, ', ...
        '<left,Bslow*direct> = %.6g%+.6gi\n'], ...
        spec.label, directResidual, leftResidual, ...
        real(mode.normalization), imag(mode.normalization));
    if directResidualDetails.fullToPhysicalNormRatio > 10
        fprintf(['  direct algebraic/full-state norm inflation = ', ...
            '%.3e (excluded from the residual denominator)\n'], ...
            directResidualDetails.fullToPhysicalNormRatio);
    end
    fprintf(['WNL mode timing %s: direct %.3f s, eigenpair %.3f s, ', ...
        'adjoint %.3f s, total %.3f s\n'],spec.label, ...
        mode.timing.directSolveSeconds, ...
        mode.timing.eigenpairRefinementSeconds, ...
        mode.timing.adjointSeconds,mode.timing.totalSeconds);
end
end

function combined = combine_refinement_passes(firstPass,secondPass,opts)
combined = secondPass;
combined.initialLambda = firstPass.initialLambda;
combined.initialResidual = firstPass.initialResidual;
combined.lambdaShift = secondPass.finalLambda-firstPass.initialLambda;
combined.steps = firstPass.steps+secondPass.steps;
combined.totalIterations = firstPass.totalIterations+ ...
    secondPass.totalIterations;
combined.lastFlag = secondPass.lastFlag;
combined.converged = secondPass.converged;
combined.escalated = true;
combined.numberOfPasses = 2;
combined.directResidualReady = secondPass.finalResidual <= ...
    opts.coefficientModeResidualTolerance;
combined.residualHistory = [firstPass.residualHistory; ...
    secondPass.residualHistory(2:end)];
combined.lambdaHistory = [firstPass.lambdaHistory; ...
    secondPass.lambdaHistory(2:end)];
combined.linearSolveResidualHistory = [ ...
    firstPass.linearSolveResidualHistory; ...
    secondPass.linearSolveResidualHistory];
combined.stepLengthHistory = [firstPass.stepLengthHistory; ...
    secondPass.stepLengthHistory];
combined.solverHistory = [firstPass.solverHistory; ...
    secondPass.solverHistory];
combined.algebraicCompletionHistory = [ ...
    firstPass.algebraicCompletionHistory; ...
    secondPass.algebraicCompletionHistory];
combined.lastAlgebraicCompletion = ...
    secondPass.lastAlgebraicCompletion;
combined.phaseConstraintResidualHistory = [ ...
    firstPass.phaseConstraintResidualHistory; ...
    secondPass.phaseConstraintResidualHistory(2:end)];
combined.descriptorRetentionHistory = [ ...
    firstPass.descriptorRetentionHistory; ...
    secondPass.descriptorRetentionHistory(2:end)];
combined.descriptorOverlapHistory = [ ...
    firstPass.descriptorOverlapHistory; ...
    secondPass.descriptorOverlapHistory(2:end)];
combined.minimumDescriptorRetention = min( ...
    combined.descriptorRetentionHistory);
combined.minimumDescriptorOverlap = min( ...
    combined.descriptorOverlapHistory);
combined.stoppedForReferenceMismatch = ...
    firstPass.stoppedForReferenceMismatch || ...
    secondPass.stoppedForReferenceMismatch;
combined.referenceDiagnostic = eigenpair_reference_diagnostic( ...
    firstPass.initialLambda,secondPass.finalLambda,opts);
combined.firstPass = firstPass;
combined.continuationPass = secondPass;
end

function [spec,block,direct,information] = ...
        refine_operating_point_eigenpair(model,spec,block,direct,opts)
% Joint Newton correction for A(lambda)*phi=0 with a phase/scale border.
validate_eigenpair_refinement_options(opts);
initialLambda = wnl_spec_lambda(spec);
referenceLambda = initialLambda;
if ~isempty(opts.eigenpairReferenceLambda)
    referenceLambda = opts.eigenpairReferenceLambda;
end
initialResidual = scaled_direct_residual(block,direct);
referenceDirect = direct;
referenceDirectNorm = norm(referenceDirect);
if ~isfinite(referenceDirectNorm) || referenceDirectNorm <= eps
    error('wnl_compute_mode:PhysicalModeLost', ...
        ['The operating-point refinement seed is zero or nonfinite. ', ...
         'It cannot define the eigenvector phase/scale constraint.']);
end
referenceDescriptor = block.Bslow*referenceDirect;
referenceDescriptorNorm = norm(referenceDescriptor);
referenceDescriptorRatio = referenceDescriptorNorm/referenceDirectNorm;
if ~isfinite(referenceDescriptorNorm) || ...
        referenceDescriptorNorm <= eps
    error('wnl_compute_mode:PhysicalModeLost', ...
        ['The operating-point refinement seed has Bslow*phi=0. ', ...
         'It is an algebraic/gauge direction rather than a physical ', ...
         'Floquet mode with a slow-time descriptor component.']);
end
[phaseRow,phaseTarget,phaseSource] = physical_eigenvector_phase_row( ...
    block,referenceDirect,spec,referenceDescriptor, ...
    referenceDescriptorNorm);
bestResidual = initialResidual;
bestDirect = direct;
bestSpec = spec;
bestBlock = block;
totalIterations = 0;
steps = 0;
lastFlag = NaN;
residualHistory = initialResidual;
lambdaHistory = initialLambda;
linearSolveResidualHistory = zeros(0,1);
stepLengthHistory = zeros(0,1);
solverHistory = cell(0,1);
algebraicCompletionHistory = cell(0,1);
lastAlgebraicCompletion = struct('attempted',false, ...
    'totalIterations',0);
lastCorrectionInformation = struct('available',false, ...
    'trialAvailable',false);
lastCorrectionTrial = struct('accepted',false,'bestResidual',Inf, ...
    'bestDescriptorRetention',0,'bestDescriptorOverlap',0, ...
    'usedAlgebraicCompletion',false);
phaseConstraintResidualHistory = abs(phaseRow*direct-phaseTarget);
descriptorRetentionHistory = 1.0;
descriptorOverlapHistory = 1.0;
stagnationCount = 0;
stoppedForReferenceMismatch = false;
skippedForInaccurateSeed = initialResidual > ...
    opts.eigenpairMaximumSeedResidualRatio*opts.modeResidualTolerance;
if skippedForInaccurateSeed
    stopReason = ['refinement skipped because the lifted mode is not a ', ...
        'safe physical Newton seed'];
    numberOfNewtonSteps = 0;
elseif initialResidual <= opts.eigenpairRefinementTolerance
    stopReason = 'eigenpair residual tolerance reached';
    numberOfNewtonSteps = 0;
else
    stopReason = 'Newton-step budget exhausted';
    numberOfNewtonSteps = opts.eigenpairRefinementMaxSteps;
end
for newtonStep = 1:numberOfNewtonSteps
    currentResidual = scaled_direct_residual(block,direct);
    if currentResidual <= opts.eigenpairRefinementTolerance
        stopReason = 'eigenpair residual tolerance reached';
        break;
    end
    [gmresCorrection,gmresInformation] = ...
        solve_eigenpair_correction(block,direct,spec,phaseRow, ...
        phaseTarget,opts,'gmres',[]);
    totalIterations = totalIterations+gmresInformation.iterations;
    correctionInformation = gmresInformation;
    correctionTrial = try_eigenpair_correction(model,block,direct, ...
        spec,gmresCorrection,gmresInformation,currentResidual,phaseRow, ...
        phaseTarget,referenceDescriptor,referenceDescriptorNorm, ...
        referenceDescriptorRatio,opts);
    if correctionTrial.algebraicCompletion.attempted
        totalIterations = totalIterations + ...
            correctionTrial.algebraicCompletion.totalIterations;
        gmresInformation.algebraicCompletion = ...
            correctionTrial.algebraicCompletion;
        if correctionTrial.usedAlgebraicCompletion
            gmresInformation.solver = ...
                [gmresInformation.solver,' + DAE algebraic completion'];
        end
    end
    correctionInformation = gmresInformation;
    if opts.verbose && correction_candidate_available(gmresInformation)
        fprintf(['WNL block-GMRES physical trial: accepted=%d, ', ...
            'best residual %.3e, descriptor retention/overlap ', ...
            '%.3e/%.3e, equation gate=%d, ', ...
            'algebraic completion=%d.\n'], ...
            correctionTrial.accepted, ...
            correctionTrial.bestResidual, ...
            correctionTrial.bestDescriptorRetention, ...
            correctionTrial.bestDescriptorOverlap, ...
            gmresInformation.available, ...
            correctionTrial.usedAlgebraicCompletion);
    elseif opts.verbose && isfield(gmresInformation,'rejectionReason') && ...
            ~isempty(gmresInformation.rejectionReason)
        fprintf('WNL block-GMRES correction unavailable: %s.\n', ...
            gmresInformation.rejectionReason);
    end

    % Do not spend LSQR work merely because GMRES missed an algebraic
    % tolerance. First test whether its inexact correction actually reduces
    % the full physical residual on the tracked descriptor branch. Only a
    % rejected physical trial activates the fallback.
    if ~correctionTrial.accepted && ...
            opts.eigenpairLsqrFallbackMaxIterations > 0
        warmStart = [];
        % Reuse a rejected GMRES correction only when its best physical
        % trial remained on the descriptor branch. A pressure-inflated
        % correction is a harmful LSQR initial iterate and defeats the
        % physical minimum-norm fallback introduced below.
        if correction_candidate_available(gmresInformation) && ...
                correctionTrial.bestDescriptorRetention >= ...
                    opts.eigenpairMinimumDescriptorRetention && ...
                correctionTrial.bestDescriptorOverlap >= ...
                    opts.eigenpairMinimumDescriptorOverlap
            warmStart = gmresCorrection;
        end
        [lsqrCorrection,lsqrInformation] = ...
            solve_eigenpair_correction(block,direct,spec,phaseRow, ...
            phaseTarget,opts,'lsqr',warmStart);
        totalIterations = totalIterations+lsqrInformation.iterations;
        lsqrTrial = try_eigenpair_correction(model,block,direct, ...
            spec,lsqrCorrection,lsqrInformation,currentResidual, ...
            phaseRow,phaseTarget,referenceDescriptor, ...
            referenceDescriptorNorm,referenceDescriptorRatio,opts);
        if lsqrTrial.algebraicCompletion.attempted
            totalIterations = totalIterations + ...
                lsqrTrial.algebraicCompletion.totalIterations;
            lsqrInformation.algebraicCompletion = ...
                lsqrTrial.algebraicCompletion;
            if lsqrTrial.usedAlgebraicCompletion
                lsqrInformation.solver = ...
                    [lsqrInformation.solver, ...
                    ' + DAE algebraic completion'];
            end
        end
        if opts.verbose && correction_candidate_available(lsqrInformation)
            fprintf(['WNL LSQR fallback physical trial: accepted=%d, ', ...
                'best residual %.3e, descriptor retention/overlap ', ...
                '%.3e/%.3e, equation gate=%d, ', ...
                'algebraic completion=%d.\n'], ...
                lsqrTrial.accepted, ...
                lsqrTrial.bestResidual, ...
                lsqrTrial.bestDescriptorRetention, ...
                lsqrTrial.bestDescriptorOverlap, ...
                lsqrInformation.available, ...
                lsqrTrial.usedAlgebraicCompletion);
        elseif opts.verbose && ...
                isfield(lsqrInformation,'rejectionReason') && ...
                ~isempty(lsqrInformation.rejectionReason)
            fprintf('WNL LSQR correction unavailable: %s.\n', ...
                lsqrInformation.rejectionReason);
        end
        if lsqrTrial.accepted || ...
                lsqrTrial.bestResidual < correctionTrial.bestResidual
            correctionTrial = lsqrTrial;
            correctionInformation = lsqrInformation;
        elseif ~correctionTrial.accepted && ...
                ~lsqrInformation.available && ...
                correctionTrial.bestDescriptorRetention < ...
                    opts.eigenpairMinimumDescriptorRetention
            % The fast correction solved its equation but left the physical
            % branch, while the pressure-safe fallback did not solve the
            % equation. Retain the fallback diagnostics so the stop reason
            % identifies algebraic nonconvergence rather than suggesting
            % that more line-search cuts will help.
            correctionTrial = lsqrTrial;
            correctionInformation = lsqrInformation;
        end
    end
    lastFlag = correctionInformation.flag;
    lastAlgebraicCompletion = correctionTrial.algebraicCompletion;
    lastCorrectionInformation = correctionInformation;
    lastCorrectionTrial = summarize_correction_trial(correctionTrial);
    accepted = correctionTrial.accepted;
    if ~accepted
        if ~correctionInformation.available
            stopReason = ['bordered correction equation did not reach ', ...
                'the required inexact-Newton tolerance'];
        else
            stopReason = ['bordered correction did not reduce the ', ...
                'residual while preserving the physical descriptor mode'];
        end
        if opts.verbose
            fprintf(['WNL eigenpair correction rejected (%s): ', ...
                'correction residual %.3e (scaled %.3e, phase %.3e), ', ...
                'best trial residual %.3e versus %.3e, descriptor ', ...
                'retention/overlap %.3e/%.3e.\n'], ...
                correctionInformation.solver, ...
                correctionInformation.equationResidual, ...
                correctionInformation.scaledEquationResidual, ...
                correctionInformation.phaseConstraintResidual, ...
                correctionTrial.bestResidual,currentResidual, ...
                correctionTrial.bestDescriptorRetention, ...
                correctionTrial.bestDescriptorOverlap);
        end
        break;
    end
    candidateDirect = correctionTrial.direct;
    candidateSpec = correctionTrial.spec;
    candidateBlock = correctionTrial.block;
    candidateResidual = correctionTrial.residual;
    candidatePhaseResidual = correctionTrial.phaseResidual;
    candidateDescriptorRetention = ...
        correctionTrial.descriptorRetention;
    candidateDescriptorOverlap = correctionTrial.descriptorOverlap;
    stepLength = correctionTrial.stepLength;
    relativeImprovement = ...
        (currentResidual-candidateResidual)/max(currentResidual,eps);
    direct = candidateDirect;
    spec = candidateSpec;
    block = candidateBlock;
    steps = newtonStep;
    residualHistory(end+1,1) = candidateResidual; %#ok<AGROW>
    lambdaHistory(end+1,1) = wnl_spec_lambda(spec); %#ok<AGROW>
    linearSolveResidualHistory(end+1,1) = ...
        correctionInformation.equationResidual; %#ok<AGROW>
    stepLengthHistory(end+1,1) = stepLength; %#ok<AGROW>
    solverHistory{end+1,1} = correctionInformation.solver; %#ok<AGROW>
    algebraicCompletionHistory{end+1,1} = ...
        correctionTrial.algebraicCompletion; %#ok<AGROW>
    phaseConstraintResidualHistory(end+1,1) = ...
        candidatePhaseResidual; %#ok<AGROW>
    descriptorRetentionHistory(end+1,1) = ...
        candidateDescriptorRetention; %#ok<AGROW>
    descriptorOverlapHistory(end+1,1) = ...
        candidateDescriptorOverlap; %#ok<AGROW>
    if opts.verbose
        fprintf(['WNL eigenpair step %d: %s, correction residual ', ...
            '%.3e (scaled %.3e, phase %.3e), step %.3g, ', ...
            'mode residual %.3e -> %.3e, ', ...
            'descriptor retention/overlap %.3e/%.3e, ', ...
            'lambda %.8g%+.3gi\n'],newtonStep, ...
            correctionInformation.solver, ...
            correctionInformation.equationResidual, ...
            correctionInformation.scaledEquationResidual, ...
            correctionInformation.phaseConstraintResidual,stepLength, ...
            currentResidual,candidateResidual, ...
            candidateDescriptorRetention,candidateDescriptorOverlap, ...
            real(wnl_spec_lambda(spec)), ...
            imag(wnl_spec_lambda(spec)));
    end
    if candidateResidual < bestResidual
        bestResidual = candidateResidual;
        bestDirect = direct;
        bestSpec = spec;
        bestBlock = block;
    end
    if relativeImprovement < ...
            opts.eigenpairStagnationRelativeImprovement
        stagnationCount = stagnationCount+1;
    else
        stagnationCount = 0;
    end
    if stagnationCount >= opts.eigenpairStagnationSteps
        stopReason = 'physical residual stagnated';
        break;
    end
    referenceDiagnostic = eigenpair_reference_diagnostic( ...
        referenceLambda,wnl_spec_lambda(spec),opts);
    lastLambdaStep = abs(lambdaHistory(end)-lambdaHistory(end-1));
    totalLambdaShift = abs(wnl_spec_lambda(spec)-referenceLambda);
    exponentShiftStable = lastLambdaStep <= ...
        opts.eigenpairReferenceMismatchMaximumLastStepRatio * ...
        max(totalLambdaShift,eps);
    reliableMismatch = candidateResidual <= ...
        opts.modeResidualTolerance && ...
        exponentShiftStable && ...
        referenceDiagnostic.absoluteMismatch > ...
        opts.eigenpairReferenceMismatchAbortFactor * ...
        referenceDiagnostic.allowedMismatch;
    if opts.enforceReducedFullEigenvalueAgreement && ...
            opts.stopEigenpairOnReferenceMismatch && ...
            (opts.eigenpairPriorAcceptedSteps+newtonStep) >= ...
                opts.eigenpairReferenceMismatchMinimumSteps && ...
            reliableMismatch
        stoppedForReferenceMismatch = true;
        stopReason = ['reduced/full exponent mismatch established at ', ...
            'linear-ready residual'];
        break;
    end
    if candidateResidual <= opts.eigenpairRefinementTolerance
        stopReason = 'eigenpair residual tolerance reached';
        break;
    end
end
direct = bestDirect;
spec = bestSpec;
block = bestBlock;
referenceDiagnostic = eigenpair_reference_diagnostic( ...
    referenceLambda,wnl_spec_lambda(spec),opts);
information = struct('attempted',true,'initialLambda',initialLambda, ...
    'referenceLambda',referenceLambda, ...
    'finalLambda',wnl_spec_lambda(spec), ...
    'lambdaShift',wnl_spec_lambda(spec)-initialLambda, ...
    'initialResidual',initialResidual,'finalResidual',bestResidual, ...
    'steps',steps,'totalIterations',totalIterations, ...
    'lastFlag',lastFlag,'converged', ...
    bestResidual <= opts.eigenpairRefinementTolerance, ...
    'residualHistory',residualHistory, ...
    'lambdaHistory',lambdaHistory, ...
    'linearSolveResidualHistory',linearSolveResidualHistory, ...
    'stepLengthHistory',stepLengthHistory, ...
    'solverHistory',{solverHistory}, ...
    'algebraicCompletionHistory',{algebraicCompletionHistory}, ...
    'lastAlgebraicCompletion',lastAlgebraicCompletion, ...
    'lastCorrectionInformation',lastCorrectionInformation, ...
    'lastCorrectionTrial',lastCorrectionTrial, ...
    'phaseConstraintResidualHistory', ...
        phaseConstraintResidualHistory, ...
    'descriptorRetentionHistory',descriptorRetentionHistory, ...
    'descriptorOverlapHistory',descriptorOverlapHistory, ...
    'minimumDescriptorRetention',min(descriptorRetentionHistory), ...
    'minimumDescriptorOverlap',min(descriptorOverlapHistory), ...
    'skippedForInaccurateSeed',skippedForInaccurateSeed, ...
    'phaseConstraintSource',phaseSource, ...
    'stoppedForReferenceMismatch',stoppedForReferenceMismatch, ...
    'referenceDiagnostic',referenceDiagnostic, ...
    'stopReason',stopReason);
end

function [phaseRow,phaseTarget,source] = ...
        physical_eigenvector_phase_row(block,direct,spec,descriptor, ...
        descriptorNorm)
% Anchor scale to interface displacement, never to pressure-dominated norm.
numberOfUnknowns = numel(direct);
phaseRow = sparse(1,numberOfUnknowns);
source = 'Bslow descriptor variables';
if isfield(spec,'prescribedDofs') && ~isempty(spec.prescribedDofs)
    localDofs = unique(spec.prescribedDofs(:));
    offsets = (0:numel(spec.n)-1)*spec.ndof;
    anchorDofs = reshape(localDofs+offsets,[],1);
    anchor = direct(anchorDofs);
    anchorNormSquared = real(anchor'*anchor);
    if isfinite(anchorNormSquared) && anchorNormSquared > eps
        phaseRow(1,anchorDofs) = anchor'/anchorNormSquared;
        source = 'prescribed interface displacement';
    end
end
if nnz(phaseRow) == 0
    % Bslow removes pressure and algebraic constraint variables. This is the
    % physical fallback for models without explicit interface DOF metadata.
    phaseRow = sparse((descriptor'/descriptorNorm^2)*block.Bslow);
end
phaseTarget = phaseRow*direct;
if ~isfinite(real(phaseTarget)) || ~isfinite(imag(phaseTarget)) || ...
        abs(phaseTarget) <= eps
    error('wnl_compute_mode:PhysicalModeLost', ...
        ['The physical interface/descriptor variables cannot define a ', ...
         'finite eigenvector phase and scale.']);
end
phaseRow = phaseRow/phaseTarget;
phaseTarget = 1.0;
end

function trial = try_eigenpair_correction(model,block,direct,spec, ...
        correction,information,currentResidual,phaseRow,phaseTarget, ...
        referenceDescriptor,referenceDescriptorNorm, ...
        referenceDescriptorRatio,opts)
% Test an inexact correction against the actual physical Floquet operator.
trial = struct('accepted',false,'direct',direct,'spec',spec, ...
    'block',block,'residual',Inf,'phaseResidual',Inf, ...
    'descriptorRetention',0,'descriptorOverlap',0, ...
    'stepLength',0,'bestResidual',Inf, ...
    'bestDescriptorRetention',0,'bestDescriptorOverlap',0, ...
    'usedAlgebraicCompletion',false, ...
    'algebraicCompletion',struct('attempted',false, ...
    'totalIterations',0));
if ~correction_candidate_available(information)
    return;
end
numberOfUnknowns = numel(direct);
stepLength = 1.0;
algebraicCompletionAttempted = false;
for lineSearchCut = 0:opts.eigenpairLineSearchMaxCuts
    candidateDirect = direct + ...
        stepLength*correction(1:numberOfUnknowns);
    candidateSpec = spec;
    candidateSpec.lambda = wnl_spec_lambda(spec) + ...
        stepLength*correction(end);
    candidateBlock = model.block(candidateSpec);
    candidateResidual = scaled_direct_residual( ...
        candidateBlock,candidateDirect);
    candidatePhaseResidual = abs( ...
        phaseRow*candidateDirect-phaseTarget);
    candidateDescriptor = candidateBlock.Bslow*candidateDirect;
    candidateDirectNorm = norm(candidateDirect);
    candidateDescriptorNorm = norm(candidateDescriptor);
    candidateDescriptorRatio = candidateDescriptorNorm/max( ...
        candidateDirectNorm,eps);
    candidateDescriptorRetention = candidateDescriptorRatio/max( ...
        referenceDescriptorRatio,eps);
    candidateDescriptorOverlap = abs( ...
        referenceDescriptor'*candidateDescriptor)/max( ...
        referenceDescriptorNorm*candidateDescriptorNorm,eps);
    physicalCandidate = isfinite(candidateDirectNorm) && ...
        candidateDirectNorm > eps && ...
        isfinite(candidatePhaseResidual) && ...
        candidatePhaseResidual <= ...
            opts.eigenpairCorrectionConstraintTolerance && ...
        isfinite(candidateDescriptorRetention) && ...
        candidateDescriptorRetention >= ...
            opts.eigenpairMinimumDescriptorRetention && ...
        isfinite(candidateDescriptorOverlap) && ...
        candidateDescriptorOverlap >= ...
            opts.eigenpairMinimumDescriptorOverlap;

    % A block-preconditioned correction can accurately update the dynamic
    % velocity/interface state while acquiring an enormous pressure or
    % gauge component. If its physical residual decreases and its Bslow
    % direction is correct, recompute only the zero-mass algebraic variables
    % by a minimum-norm DAE completion. The descriptor-supported variables,
    % interface phase/scale, lambda, and every governing row remain fixed.
    inflatedAlgebraicState = ~physicalCandidate && ...
        isfinite(candidateResidual) && ...
        candidateResidual < currentResidual && ...
        isfinite(candidatePhaseResidual) && ...
        candidatePhaseResidual <= ...
            opts.eigenpairCorrectionConstraintTolerance && ...
        isfinite(candidateDescriptorOverlap) && ...
        candidateDescriptorOverlap >= ...
            opts.eigenpairMinimumDescriptorOverlap && ...
        isfinite(candidateDescriptorRetention) && ...
        candidateDescriptorRetention < ...
            opts.eigenpairMinimumDescriptorRetention;
    if opts.eigenpairUseAlgebraicCompletion && ...
            inflatedAlgebraicState && ~algebraicCompletionAttempted
        algebraicCompletionAttempted = true;
        preservedDofs = expanded_prescribed_dofs(candidateSpec);
        try
            [completedDirect,completionInformation] = ...
                wnl_complete_algebraic_state(candidateBlock.A, ...
                candidateBlock.Bslow,candidateDirect,preservedDofs,opts);
        catch completionError
            completedDirect = candidateDirect;
            completionInformation = struct('attempted',true, ...
                'available',false,'valid',false,'totalIterations',0, ...
                'initialResidualNorm',norm( ...
                    candidateBlock.A*candidateDirect), ...
                'finalResidualNorm',Inf, ...
                'initialFullNorm',norm(candidateDirect), ...
                'finalFullNorm',Inf, ...
                'errorIdentifier',completionError.identifier, ...
                'errorMessage',completionError.message);
            if opts.verbose
                warning('wnl_compute_mode:AlgebraicCompletionFailed', ...
                    'DAE algebraic completion failed: %s', ...
                    completionError.message);
            end
        end
        trial.algebraicCompletion = completionInformation;
        if opts.verbose && completionInformation.attempted
            fprintf(['WNL DAE algebraic completion: residual norm ', ...
                '%.3e -> %.3e, full-state norm %.3e -> %.3e, ', ...
                'iterations = %d, available/valid = %d/%d.\n'], ...
                completionInformation.initialResidualNorm, ...
                completionInformation.finalResidualNorm, ...
                completionInformation.initialFullNorm, ...
                completionInformation.finalFullNorm, ...
                completionInformation.totalIterations, ...
                completionInformation.available, ...
                completionInformation.valid);
        end
        if completionInformation.available && ...
                completionInformation.valid
            completedResidual = scaled_direct_residual( ...
                candidateBlock,completedDirect);
            completedPhaseResidual = abs( ...
                phaseRow*completedDirect-phaseTarget);
            completedDescriptor = ...
                candidateBlock.Bslow*completedDirect;
            completedDirectNorm = norm(completedDirect);
            completedDescriptorNorm = norm(completedDescriptor);
            completedDescriptorRatio = completedDescriptorNorm / ...
                max(completedDirectNorm,eps);
            completedDescriptorRetention = ...
                completedDescriptorRatio/max(referenceDescriptorRatio,eps);
            completedDescriptorOverlap = abs( ...
                referenceDescriptor'*completedDescriptor) / max( ...
                referenceDescriptorNorm*completedDescriptorNorm,eps);
            completedPhysicalCandidate = ...
                isfinite(completedDirectNorm) && ...
                completedDirectNorm > eps && ...
                isfinite(completedPhaseResidual) && ...
                completedPhaseResidual <= ...
                    opts.eigenpairCorrectionConstraintTolerance && ...
                isfinite(completedDescriptorRetention) && ...
                completedDescriptorRetention >= ...
                    opts.eigenpairMinimumDescriptorRetention && ...
                isfinite(completedDescriptorOverlap) && ...
                completedDescriptorOverlap >= ...
                    opts.eigenpairMinimumDescriptorOverlap;
            if completedPhysicalCandidate && ...
                    isfinite(completedResidual) && ...
                    completedResidual < currentResidual
                candidateDirect = completedDirect;
                candidateResidual = completedResidual;
                candidatePhaseResidual = completedPhaseResidual;
                candidateDirectNorm = completedDirectNorm;
                candidateDescriptorNorm = completedDescriptorNorm;
                candidateDescriptorRetention = ...
                    completedDescriptorRetention;
                candidateDescriptorOverlap = completedDescriptorOverlap;
                physicalCandidate = true;
                trial.usedAlgebraicCompletion = true;
            end
        end
    end
    if isfinite(candidateResidual) && candidateResidual < trial.bestResidual
        trial.bestResidual = candidateResidual;
        trial.bestDescriptorRetention = candidateDescriptorRetention;
        trial.bestDescriptorOverlap = candidateDescriptorOverlap;
    end
    if physicalCandidate && isfinite(candidateResidual) && ...
            candidateResidual < currentResidual
        trial.accepted = true;
        trial.direct = candidateDirect;
        trial.spec = candidateSpec;
        trial.block = candidateBlock;
        trial.residual = candidateResidual;
        trial.phaseResidual = candidatePhaseResidual;
        trial.descriptorRetention = candidateDescriptorRetention;
        trial.descriptorOverlap = candidateDescriptorOverlap;
        trial.stepLength = stepLength;
        return;
    end
    stepLength = 0.5*stepLength;
end
end

function tf = correction_candidate_available(information)
tf = isfield(information,'available') && information.available;
if isfield(information,'trialAvailable')
    tf = tf || information.trialAvailable;
end
end

function summary = summarize_correction_trial(trial)
summary = struct('accepted',trial.accepted, ...
    'residual',trial.residual,'phaseResidual',trial.phaseResidual, ...
    'descriptorRetention',trial.descriptorRetention, ...
    'descriptorOverlap',trial.descriptorOverlap, ...
    'stepLength',trial.stepLength, ...
    'bestResidual',trial.bestResidual, ...
    'bestDescriptorRetention',trial.bestDescriptorRetention, ...
    'bestDescriptorOverlap',trial.bestDescriptorOverlap, ...
    'usedAlgebraicCompletion',trial.usedAlgebraicCompletion, ...
    'algebraicCompletion',trial.algebraicCompletion);
end

function dofs = expanded_prescribed_dofs(spec)
dofs = zeros(0,1);
if ~isfield(spec,'prescribedDofs') || isempty(spec.prescribedDofs)
    return;
end
localDofs = unique(spec.prescribedDofs(:));
offsets = (0:numel(spec.n)-1)*spec.ndof;
dofs = reshape(localDofs+offsets,[],1);
end

function [correction,information] = ...
        solve_eigenpair_correction(block,direct,spec,phaseRow, ...
        phaseTarget,opts,solverChoice,initialCorrection)
% Solve [A B*phi; c' 0]*[dphi;dlambda]=[-A*phi;1-c'*phi].
if ~ismember(solverChoice,{'gmres','lsqr'})
    error('wnl_compute_mode:EigenpairCorrectionSolver', ...
        'solverChoice must be gmres or lsqr.');
end
numberOfUnknowns = numel(direct);
bordered = [block.A,sparse(block.Bslow*direct); ...
    sparse(phaseRow),sparse(1,1)];
phaseDefect = phaseTarget-phaseRow*direct;
rhs = [-block.A*direct;phaseDefect];
[rowScaledMatrix,scaledRhs] = equilibrate_equations(bordered,rhs);
[scaledMatrix,columnScale] = equilibrate_columns(rowScaledMatrix);
scaledCorrection = complex(zeros(numberOfUnknowns+1,1));
physicalCorrectionGuess = complex(zeros(numberOfUnknowns+1,1));
if ~isempty(initialCorrection)
    if numel(initialCorrection) ~= numberOfUnknowns+1
        error('wnl_compute_mode:EigenpairWarmStartSize', ...
            'The correction warm start has the wrong number of entries.');
    end
    initialCorrection = initialCorrection(:);
    if all(isfinite(real(initialCorrection))) && ...
            all(isfinite(imag(initialCorrection)))
        scaledCorrection = initialCorrection./columnScale;
        physicalCorrectionGuess = initialCorrection;
    end
end
bestPhysicalCorrection = [];
bestEquationResidual = Inf;
bestFlag = NaN;
bestSolver = 'unavailable';
totalIterations = 0;
gmresInformation = struct('attempted',false,'accepted',false);

numberOfHarmonics = numel(spec.n);
canUseBlockGmres = opts.eigenpairUseBlockGmres && ...
    numberOfHarmonics > 1 && ...
    spec.ndof*numberOfHarmonics == numberOfUnknowns;
if strcmp(solverChoice,'gmres') && canUseBlockGmres
    gmresInformation.attempted = true;
    try
        [blockFactors,blockRegularization,blockInverseGain] = ...
            factor_temporal_diagonal_blocks(scaledMatrix,spec.ndof, ...
            numberOfHarmonics,opts);
        [bottomBorder,borderResponse,borderSchur] = ...
            factor_bordered_block_jacobi(scaledMatrix,blockFactors, ...
            spec.ndof,numberOfHarmonics);
        preconditioner = @(rightHandSideValue) ...
            apply_bordered_block_jacobi_inverse(rightHandSideValue, ...
            blockFactors,spec.ndof,numberOfHarmonics,bottomBorder, ...
            borderResponse,borderSchur);
        [gmresCandidate,gmresFlag,gmresRelativeResidual, ...
            gmresIteration,gmresResidualHistory] = gmres( ...
            scaledMatrix,scaledRhs,opts.eigenpairGmresRestart, ...
            opts.eigenpairRefinementSolveTolerance, ...
            opts.eigenpairGmresMaxCycles,preconditioner,[], ...
            scaledCorrection);
        gmresIterations = gmres_iteration_count( ...
            gmresIteration,opts.eigenpairGmresRestart);
        totalIterations = totalIterations+gmresIterations;
        gmresEquationResidual = norm( ...
            scaledMatrix*gmresCandidate-scaledRhs) / ...
            max(norm(scaledRhs),eps);
        finiteGmres = all(isfinite(real(gmresCandidate))) && ...
            all(isfinite(imag(gmresCandidate)));
        if finiteGmres
            bestPhysicalCorrection = columnScale.*gmresCandidate;
            bestEquationResidual = gmresEquationResidual;
            bestFlag = gmresFlag;
            bestSolver = 'block-GMRES';
        end
        gmresInformation.flag = gmresFlag;
        gmresInformation.relativeResidual = gmresRelativeResidual;
        gmresInformation.equationResidual = gmresEquationResidual;
        gmresInformation.iteration = gmresIteration;
        gmresInformation.iterations = gmresIterations;
        gmresInformation.residualHistory = gmresResidualHistory;
        gmresInformation.blockRegularization = blockRegularization;
        gmresInformation.blockInverseGain = blockInverseGain;
        gmresInformation.borderSchurComplement = borderSchur;
        gmresInformation.accepted = finiteGmres && ...
            gmresEquationResidual <= ...
            opts.eigenpairGmresAcceptanceTolerance;
    catch gmresError
        gmresInformation.errorIdentifier = gmresError.identifier;
        gmresInformation.errorMessage = gmresError.message;
    end
end

lsqrInformation = struct('attempted',false);
if strcmp(solverChoice,'lsqr') && ...
        opts.eigenpairLsqrFallbackMaxIterations > 0
    % Add the physical correction norm to the least-squares objective before
    % column equilibration:
    %
    %   min_delta ||R(K*delta-rhs)||^2 + alpha||delta_q||^2.
    %
    % Column scaling of this complete objective improves conditioning but
    % does not change the physical Tikhonov norm. This avoids both extremes
    % seen in earlier releases: a fast scaled solve with an enormous pressure
    % component and an unscaled physical LSQR solve whose bordered residual
    % remained O(1) after hundreds of iterations.
    lsqrInformation.attempted = true;
    correctionRegularization = ...
        opts.eigenpairCorrectionRegularization;
    if correctionRegularization > 0
        regularizationRows = [ ...
            sqrt(correctionRegularization)*speye(numberOfUnknowns), ...
            sparse(numberOfUnknowns,1)];
        lsqrObjectiveMatrix = [rowScaledMatrix;regularizationRows];
        lsqrObjectiveRhs = [scaledRhs; ...
            complex(zeros(numberOfUnknowns,1))];
        [lsqrMatrix,lsqrColumnScale] = ...
            equilibrate_columns(lsqrObjectiveMatrix);
    else
        lsqrMatrix = rowScaledMatrix;
        lsqrObjectiveRhs = scaledRhs;
        lsqrColumnScale = ones(numberOfUnknowns+1,1);
    end
    scaledLsqrGuess = physicalCorrectionGuess./lsqrColumnScale;
    for fallbackAttempt = 0:opts.eigenpairLsqrFallbackMaxRestarts
        [lsqrCandidate,lsqrFlag,lsqrRelativeResidual,iterations] = ...
            lsqr(lsqrMatrix,lsqrObjectiveRhs, ...
            opts.eigenpairRefinementSolveTolerance, ...
            opts.eigenpairLsqrFallbackMaxIterations,[],[], ...
            scaledLsqrGuess);
        totalIterations = totalIterations+iterations;
        physicalLsqrCandidate = lsqrColumnScale.*lsqrCandidate;
        lsqrEquationResidual = norm( ...
            rowScaledMatrix*physicalLsqrCandidate-scaledRhs) / ...
            max(norm(scaledRhs),eps);
        lsqrAugmentedResidual = norm( ...
            lsqrMatrix*lsqrCandidate-lsqrObjectiveRhs) / ...
            max(norm(lsqrObjectiveRhs),eps);
        finiteLsqr = all(isfinite(real(lsqrCandidate))) && ...
            all(isfinite(imag(lsqrCandidate)));
        if finiteLsqr && lsqrEquationResidual < bestEquationResidual
            bestPhysicalCorrection = physicalLsqrCandidate;
            bestEquationResidual = lsqrEquationResidual;
            bestFlag = lsqrFlag;
            bestSolver = 'regularized LSQR fallback';
        end
        physicalCorrectionGuess = physicalLsqrCandidate;
        scaledLsqrGuess = lsqrCandidate;
        lsqrInformation.flag = lsqrFlag;
        lsqrInformation.relativeResidual = lsqrRelativeResidual;
        lsqrInformation.equationResidual = lsqrEquationResidual;
        lsqrInformation.augmentedResidual = lsqrAugmentedResidual;
        lsqrInformation.iterations = iterations;
        lsqrInformation.attempts = fallbackAttempt+1;
        lsqrInformation.regularization = correctionRegularization;
        lsqrInformation.columnScaleRange = ...
            positive_range(lsqrColumnScale);
        if lsqrFlag == 0 || lsqrEquationResidual <= ...
                opts.eigenpairCorrectionEquationTolerance
            break;
        end
    end
end

available = ~isempty(bestPhysicalCorrection) && ...
    all(isfinite(real(bestPhysicalCorrection))) && ...
    all(isfinite(imag(bestPhysicalCorrection)));
if available
    correction = bestPhysicalCorrection;
    % Iterative least-squares convergence is dominated by the many physical
    % rows, so a small reported global residual may still contain an O(1)
    % error in the single phase/scale row. Enforce that row algebraically.
    scaleDirection = direct;
    scaleDenominator = phaseRow*scaleDirection;
    if abs(scaleDenominator) <= eps
        available = false;
        correction = complex(zeros(numberOfUnknowns+1,1));
    else
        correction(1:numberOfUnknowns) = ...
            correction(1:numberOfUnknowns) + scaleDirection * ...
            ((phaseDefect-phaseRow*correction(1:numberOfUnknowns)) / ...
            scaleDenominator);
    end
else
    correction = complex(zeros(numberOfUnknowns+1,1));
end
trialAvailable = available;
if trialAvailable
    physicalCorrectionResidual = bordered*correction-rhs;
    phaseConstraintResidual = abs(physicalCorrectionResidual(end));
    topEquationResidual = norm( ...
        physicalCorrectionResidual(1:numberOfUnknowns)) / ...
        max(norm(rhs(1:numberOfUnknowns)),eps);
    available = isfinite(topEquationResidual) && ...
        isfinite(phaseConstraintResidual) && ...
        topEquationResidual <= ...
            opts.eigenpairCorrectionEquationTolerance && ...
        phaseConstraintResidual <= ...
            opts.eigenpairCorrectionConstraintTolerance;
else
    topEquationResidual = Inf;
    phaseConstraintResidual = Inf;
end
information = struct('available',available,'solver',bestSolver, ...
    'trialAvailable',trialAvailable, ...
    'flag',bestFlag,'equationResidual',topEquationResidual, ...
    'scaledEquationResidual',bestEquationResidual, ...
    'phaseConstraintResidual',phaseConstraintResidual, ...
    'iterations',totalIterations,'gmres',gmresInformation, ...
    'lsqr',lsqrInformation);
if ~available && isfinite(topEquationResidual) && ...
        topEquationResidual > opts.eigenpairCorrectionEquationTolerance
    information.rejectionReason = sprintf([ ...
        'bordered equation residual %.3e exceeds tolerance %.3e'], ...
        topEquationResidual,opts.eigenpairCorrectionEquationTolerance);
else
    information.rejectionReason = '';
end
end

function diagnostic = eigenpair_reference_diagnostic( ...
        initialLambda,finalLambda,opts)
probeMode.spec = struct('lambda',finalLambda, ...
    'label','eigenpair-refinement probe');
probeMode.tracking.eigenpairRefinement = struct( ...
    'attempted',true,'initialLambda',initialLambda);
diagnostic = wnl_reference_eigenvalue_consistency(probeMode,opts);
end

function validate_eigenpair_refinement_options(opts)
assert((islogical(opts.eigenpairUseBlockGmres) && ...
    isscalar(opts.eigenpairUseBlockGmres)) || ...
    (isnumeric(opts.eigenpairUseBlockGmres) && ...
    isscalar(opts.eigenpairUseBlockGmres) && ...
    isfinite(opts.eigenpairUseBlockGmres) && ...
    ismember(opts.eigenpairUseBlockGmres,[0,1])), ...
    'opts.eigenpairUseBlockGmres must be a logical scalar.');
assert((islogical(opts.eigenpairUseAlgebraicCompletion) && ...
    isscalar(opts.eigenpairUseAlgebraicCompletion)) || ...
    (isnumeric(opts.eigenpairUseAlgebraicCompletion) && ...
    isscalar(opts.eigenpairUseAlgebraicCompletion) && ...
    isfinite(opts.eigenpairUseAlgebraicCompletion) && ...
    ismember(opts.eigenpairUseAlgebraicCompletion,[0,1])), ...
    'opts.eigenpairUseAlgebraicCompletion must be a logical scalar.');
assert((islogical(opts.stopEigenpairOnReferenceMismatch) && ...
    isscalar(opts.stopEigenpairOnReferenceMismatch)) || ...
    (isnumeric(opts.stopEigenpairOnReferenceMismatch) && ...
    isscalar(opts.stopEigenpairOnReferenceMismatch) && ...
    isfinite(opts.stopEigenpairOnReferenceMismatch) && ...
    ismember(opts.stopEigenpairOnReferenceMismatch,[0,1])), ...
    'opts.stopEigenpairOnReferenceMismatch must be a logical scalar.');
validateattributes(opts.eigenpairRefinementMaxSteps,{'numeric'}, ...
    {'scalar','integer','positive'});
validateattributes(opts.eigenpairGmresRestart,{'numeric'}, ...
    {'scalar','integer','positive'});
validateattributes(opts.eigenpairGmresMaxCycles,{'numeric'}, ...
    {'scalar','integer','positive'});
validateattributes(opts.eigenpairGmresAcceptanceTolerance,{'numeric'}, ...
    {'scalar','real','positive','finite'});
validateattributes(opts.eigenpairLsqrFallbackMaxIterations,{'numeric'}, ...
    {'scalar','integer','nonnegative'});
validateattributes(opts.eigenpairLsqrFallbackMaxRestarts,{'numeric'}, ...
    {'scalar','integer','nonnegative'});
validateattributes(opts.eigenpairCorrectionRegularization,{'numeric'}, ...
    {'scalar','real','nonnegative','finite'});
validateattributes(opts.eigenpairCorrectionEquationTolerance,{'numeric'}, ...
    {'scalar','real','positive','<',1,'finite'});
validateattributes( ...
    opts.eigenpairAlgebraicCompletionRegularization,{'numeric'}, ...
    {'scalar','real','nonnegative','finite'});
validateattributes( ...
    opts.eigenpairAlgebraicCompletionSolveTolerance,{'numeric'}, ...
    {'scalar','real','positive','finite'});
validateattributes( ...
    opts.eigenpairAlgebraicCompletionEquationTolerance,{'numeric'}, ...
    {'scalar','real','positive','<',1,'finite'});
validateattributes( ...
    opts.eigenpairAlgebraicCompletionMaxIterations,{'numeric'}, ...
    {'scalar','integer','nonnegative'});
validateattributes( ...
    opts.eigenpairAlgebraicCompletionMaxRestarts,{'numeric'}, ...
    {'scalar','integer','nonnegative'});
validateattributes(opts.eigenpairLineSearchMaxCuts,{'numeric'}, ...
    {'scalar','integer','nonnegative'});
validateattributes(opts.eigenpairStagnationRelativeImprovement, ...
    {'numeric'},{'scalar','real','nonnegative','<',1,'finite'});
validateattributes(opts.eigenpairStagnationSteps,{'numeric'}, ...
    {'scalar','integer','positive'});
validateattributes(opts.eigenpairCorrectionConstraintTolerance, ...
    {'numeric'},{'scalar','real','positive','finite'});
validateattributes(opts.eigenpairMinimumDescriptorRetention, ...
    {'numeric'},{'scalar','real','positive','<=',1,'finite'});
validateattributes(opts.eigenpairMinimumDescriptorOverlap, ...
    {'numeric'},{'scalar','real','nonnegative','<',1,'finite'});
validateattributes(opts.eigenpairMaximumSeedResidualRatio, ...
    {'numeric'},{'scalar','real','>=',1,'finite'});
validateattributes(opts.eigenpairReferenceMismatchAbortFactor, ...
    {'numeric'},{'scalar','real','>=',1,'finite'});
validateattributes(opts.eigenpairReferenceMismatchMinimumSteps, ...
    {'numeric'},{'scalar','integer','positive'});
validateattributes( ...
    opts.eigenpairReferenceMismatchMaximumLastStepRatio,{'numeric'}, ...
    {'scalar','real','positive','<=',1,'finite'});
if ~isempty(opts.eigenpairReferenceLambda)
    validateattributes(opts.eigenpairReferenceLambda,{'numeric'}, ...
        {'scalar','finite'});
end
validateattributes(opts.eigenpairPriorAcceptedSteps,{'numeric'}, ...
    {'scalar','integer','nonnegative'});
end

function value = scaled_direct_residual(block,direct)
value = wnl_descriptor_residual( ...
    block.A,block.Bslow,direct,'direct');
end

function [left, sigma, information] = ...
        bordered_adjoint_null(A, Bslow, direct, spec, opts)
%BORDERED_ADJOINT_NULL Solve the normalized algebraic adjoint equations.
%
% For a simple neutral mode, the bordered matrix
%
%   [ A'                 directUnit ]
%   [ pairingUnit'          0       ]
%
% is nonsingular even though A is singular. Here
% pairingUnit=Bslow*direct/||Bslow*direct||. The final normalization in the
% caller converts this convenient unit constraint to
% left'*Bslow*direct=1.

numberOfUnknowns = size(A, 1);
[~,directResidualDetails] = wnl_descriptor_residual( ...
    A,Bslow,direct,'direct');
directNorm = directResidualDetails.physicalVectorNorm;
if ~isfinite(directNorm) || directNorm <= eps
    error('wnl_compute_mode:ZeroDirectForAdjoint', ...
        ['The direct vector has no finite physical descriptor-supported ', ...
         'component, so the adjoint cannot be paired.']);
end
directUnit = direct/directNorm;
pairing = Bslow*directUnit;
pairingNorm = norm(pairing);
if pairingNorm <= eps
    error('wnl_compute_mode:ZeroDescriptorPairingSeed', ...
        ['Bslow*direct is zero. The selected direct mode has no slow-time ', ...
         'descriptor component and cannot define a Landau solvability ', ...
         'normalization.']);
end
pairingUnit = pairing/pairingNorm;

validateattributes(opts.modeTrackingSolveTolerance, {'numeric'}, ...
    {'scalar', 'real', 'positive', 'finite'});
validateattributes(opts.modeTrackingMaxIterations, {'numeric'}, ...
    {'scalar', 'real', 'integer', 'positive'});
validateattributes(opts.adjointBorderedMaxRestarts, {'numeric'}, ...
    {'scalar', 'real', 'integer', 'nonnegative'});
validateattributes(opts.adjointGmresRestart, {'numeric'}, ...
    {'scalar', 'real', 'integer', 'positive'});
validateattributes(opts.adjointGmresMaxCycles, {'numeric'}, ...
    {'scalar', 'real', 'integer', 'positive'});
validateattributes(opts.adjointBlockRegularization, {'numeric'}, ...
    {'scalar', 'real', 'positive', 'finite'});
validateattributes(opts.adjointBlockRegularizationGrowth, {'numeric'}, ...
    {'scalar', 'real', '>', 1, 'finite'});
validateattributes(opts.adjointBlockRegularizationAttempts, {'numeric'}, ...
    {'scalar', 'real', 'integer', 'positive'});
validateattributes(opts.adjointBlockMaximumInverseGain, {'numeric'}, ...
    {'scalar', 'real', 'positive', 'finite'});
assert(islogical(opts.adjointUseBlockGmres) || ...
    (isnumeric(opts.adjointUseBlockGmres) && ...
    isscalar(opts.adjointUseBlockGmres)), ...
    'opts.adjointUseBlockGmres must be a logical scalar.');

borderedMatrix = [A', sparse(directUnit); ...
    sparse(pairingUnit'), sparse(1, 1)];
rightHandSide = [complex(zeros(numberOfUnknowns, 1)); 1];
[scaledMatrix, scaledRightHandSide, rowScale] = ...
    equilibrate_equations(borderedMatrix, rightHandSide);
[scaledMatrix, columnScale] = equilibrate_columns(scaledMatrix);

scaledSolution = complex(zeros(numberOfUnknowns+1, 1));
operatorScale = max(1.0,deterministic_matrix_scale(A));
% Construct the primary adjoint to the coefficient-level tolerance during
% the first solve. Stopping at the looser plotting/linear gate only to fail
% immediately in wnl_analyze_* wastes a complete mode reconstruction.
targetResidual = min(opts.modeResidualTolerance, ...
    opts.coefficientModeResidualTolerance);
constraintTolerance = max(targetResidual, ...
    100*opts.modeTrackingSolveTolerance);
flag = NaN;
relativeResidual = Inf;
totalIterations = 0;
restartsUsed = 0;
scaledResidual = Inf;
constraintResidual = Inf;
candidateValid = false;
left = complex(zeros(numberOfUnknowns, 1));
borderMultiplier = complex(NaN);
sigma = Inf;
solver = 'LSQR';
gmresInformation = struct();
gmresInformation.attempted = false;
gmresInformation.succeeded = false;

% The full Floquet matrix is block tridiagonal in temporal harmonic. Its
% diagonal blocks are the uncoupled spatial Stokes operators. Factor those
% blocks once and use their inverse inside a bordered block-Jacobi
% preconditioner.  The scalar Schur complement includes both the top border
% column and the normalization row.  This is important: treating the scalar
% border as an identity leaves the normalization residual essentially
% unpreconditioned even after the physical adjoint equation has improved.
numberOfHarmonics = numel(spec.n);
canUseBlockGmres = opts.adjointUseBlockGmres && ...
    numberOfHarmonics > 1 && ...
    spec.ndof*numberOfHarmonics == numberOfUnknowns;
if canUseBlockGmres
    gmresInformation.attempted = true;
    try
        if opts.verbose
            fprintf(['WNL adjoint preconditioner: factoring %d temporal ', ...
                'blocks of size %d.\n'], numberOfHarmonics, spec.ndof);
        end
        [blockFactors, blockRegularization, blockInverseGain] = ...
            factor_temporal_diagonal_blocks(scaledMatrix, spec.ndof, ...
            numberOfHarmonics, opts);
        [bottomBorder, borderResponse, borderSchur] = ...
            factor_bordered_block_jacobi(scaledMatrix, blockFactors, ...
            spec.ndof, numberOfHarmonics);
        if opts.verbose
            fprintf(['WNL adjoint preconditioner: regularization range ', ...
                '[%.3e, %.3e], maximum probe inverse gain %.3e.\n'], ...
                min(blockRegularization), max(blockRegularization), ...
                max(blockInverseGain));
            fprintf(['WNL adjoint preconditioner: bordered Schur ', ...
                'complement = %.6g%+.6gi.\n'], ...
                real(borderSchur), imag(borderSchur));
        end
        preconditioner = @(rightHandSideValue) ...
            apply_bordered_block_jacobi_inverse(rightHandSideValue, ...
            blockFactors, spec.ndof, numberOfHarmonics, ...
            bottomBorder, borderResponse, borderSchur);
        [scaledSolution, gmresFlag, gmresRelativeResidual, ...
            gmresIteration, gmresResidualHistory] = gmres( ...
            scaledMatrix, scaledRightHandSide, ...
            opts.adjointGmresRestart, ...
            opts.modeTrackingSolveTolerance, ...
            opts.adjointGmresMaxCycles, preconditioner, [], ...
            scaledSolution);
        physicalSolution = columnScale.*scaledSolution;
        left = physicalSolution(1:numberOfUnknowns);
        borderMultiplier = physicalSolution(end);
        [sigma, scaledResidual, constraintResidual, candidateValid] = ...
            adjoint_candidate_metrics(A, Bslow, left, borderMultiplier, ...
            pairingUnit, targetResidual, ...
            constraintTolerance, opts.nullTolerance);
        gmresIterations = gmres_iteration_count( ...
            gmresIteration, opts.adjointGmresRestart);
        totalIterations = gmresIterations;
        flag = gmresFlag;
        relativeResidual = gmresRelativeResidual;
        solver = 'block-GMRES';
        gmresInformation.flag = gmresFlag;
        gmresInformation.relativeResidual = gmresRelativeResidual;
        gmresInformation.iteration = gmresIteration;
        gmresInformation.iterations = gmresIterations;
        gmresInformation.residualHistory = gmresResidualHistory;
        % The physical residual and normalization row are the acceptance
        % tests.  A flag-1 (maximum Krylov cycles) candidate is still usable
        % when both of those independently evaluated tests pass.
        gmresInformation.succeeded = candidateValid;
        gmresInformation.candidateValid = candidateValid;
        gmresInformation.constraintResidual = constraintResidual;
        gmresInformation.blockRegularization = blockRegularization;
        gmresInformation.blockInverseGain = blockInverseGain;
        gmresInformation.borderSchurComplement = borderSchur;
        gmresInformation.preconditioner = ...
            'regularized bordered block-Jacobi';
    catch gmresError
        gmresInformation.succeeded = false;
        gmresInformation.errorIdentifier = gmresError.identifier;
        gmresInformation.errorMessage = gmresError.message;
        if opts.verbose
            warning('wnl_compute_mode:BlockGmresUnavailable', ...
                ['The temporal-block GMRES adjoint preconditioner could ', ...
                 'not be used (%s). Continuing with bordered LSQR.'], ...
                gmresError.message);
        end
    end
end

if ~candidateValid
    if opts.verbose && isfield(gmresInformation, 'flag')
        warning('wnl_compute_mode:BlockGmresCandidateRejected', ...
            ['Rejecting the block-GMRES adjoint candidate: flag %d, ', ...
             'scaled residual %.3e, normalization-row residual %.3e. ', ...
             'Continuing with bordered LSQR refinement.'], ...
            gmresInformation.flag, scaledResidual, constraintResidual);
    end
    if strcmp(solver, 'block-GMRES')
        solver = 'block-GMRES + LSQR refinement';
    end
    if any(~isfinite(real(scaledSolution))) || ...
            any(~isfinite(imag(scaledSolution)))
        scaledSolution = complex(zeros(numberOfUnknowns+1, 1));
    end
    for attempt = 0:opts.adjointBorderedMaxRestarts
        [scaledSolution, flag, relativeResidual, iterations] = lsqr( ...
            scaledMatrix, scaledRightHandSide, ...
            opts.modeTrackingSolveTolerance, ...
            opts.modeTrackingMaxIterations, [], [], scaledSolution);
        totalIterations = totalIterations+iterations;
        physicalSolution = columnScale.*scaledSolution;
        left = physicalSolution(1:numberOfUnknowns);
        borderMultiplier = physicalSolution(end);
        [sigma, scaledResidual, constraintResidual, candidateValid] = ...
            adjoint_candidate_metrics(A, Bslow, left, borderMultiplier, ...
            pairingUnit, targetResidual, ...
            constraintTolerance, opts.nullTolerance);
        restartsUsed = attempt;
        if candidateValid
            break;
        end
    end
end

information = struct();
information.method = 'exactly normalized bordered adjoint';
information.operatorScale = operatorScale;
information.effectiveSingularValue = sigma;
information.scaledResidual = scaledResidual;
information.borderMultiplier = borderMultiplier;
information.constraintResidual = constraintResidual;
information.constraintTolerance = constraintTolerance;
information.candidateValid = candidateValid;
information.solver = solver;
information.flag = flag;
information.relativeResidual = relativeResidual;
information.iterations = totalIterations;
information.restarts = restartsUsed;
information.maximumRestarts = opts.adjointBorderedMaxRestarts;
information.gmres = gmresInformation;
information.rowScaleRange = positive_range(rowScale);
information.columnScaleRange = positive_range(columnScale);

if ~candidateValid && opts.verbose
    warning('wnl_compute_mode:BorderedAdjointNotConverged', ...
        ['The bordered adjoint solver (%s) returned flag %d after %d ', ...
         'total iterations and %d restarts. Scaled adjoint residual ', ...
         '%.3e, normalization-row residual %.3e. The mode residual gate ', ...
         'will prevent nonlinear coefficients if this remains too large.'], ...
        solver, flag, totalIterations, restartsUsed, scaledResidual, ...
        constraintResidual);
end
end

function [factors, regularization, inverseGain] = ...
        factor_temporal_diagonal_blocks( ...
        borderedMatrix, ndof, numberOfHarmonics, opts)
factors = cell(numberOfHarmonics, 1);
regularization = zeros(numberOfHarmonics, 1);
inverseGain = inf(numberOfHarmonics, 1);
identity = speye(ndof);
probeIndex = (1:ndof).';
probe = [complex(ones(ndof, 1)), ...
    exp(1i*sqrt(2)*probeIndex)];
probeNorm = sqrt(sum(abs(probe).^2, 1));
for harmonicIndex = 1:numberOfHarmonics
    indices = (harmonicIndex-1)*ndof+(1:ndof);
    diagonalBlock = borderedMatrix(indices, indices);
    blockScale = max(deterministic_matrix_scale(diagonalBlock), 1.0);
    lastMessage = '';
    for attempt = 1:opts.adjointBlockRegularizationAttempts
        shift = opts.adjointBlockRegularization*blockScale * ...
            opts.adjointBlockRegularizationGrowth^(attempt-1);
        shiftedBlock = diagonalBlock+shift*identity;
        try
            trialFactor = decomposition(shiftedBlock, 'lu');
            trialSolution = trialFactor\probe;
            solutionNorm = sqrt(sum(abs(trialSolution).^2, 1));
            trialGain = max(solutionNorm./probeNorm);
            trialResidual = shiftedBlock*trialSolution-probe;
            relativeTrialResidual = max( ...
                sqrt(sum(abs(trialResidual).^2, 1))./probeNorm);
            finiteTrial = all(isfinite(real(trialSolution(:)))) && ...
                all(isfinite(imag(trialSolution(:))));
            if finiteTrial && ...
                    trialGain <= opts.adjointBlockMaximumInverseGain && ...
                    relativeTrialResidual <= 1.0e-5
                factors{harmonicIndex} = trialFactor;
                regularization(harmonicIndex) = shift;
                inverseGain(harmonicIndex) = trialGain;
                break;
            end
            lastMessage = sprintf([ ...
                'inverse gain %.3e, factor residual %.3e'], ...
                trialGain, relativeTrialResidual);
        catch factorError
            lastMessage = factorError.message;
        end
    end
    if isempty(factors{harmonicIndex})
        error('wnl_compute_mode:BlockPreconditionerFactorization', ...
            ['Could not construct a finite regularized inverse for ', ...
             'temporal block %d after %d attempts (%s).'], ...
            harmonicIndex, opts.adjointBlockRegularizationAttempts, ...
            lastMessage);
    end
end
end

function [bottomBorder, borderResponse, borderSchur] = ...
        factor_bordered_block_jacobi( ...
        borderedMatrix, factors, ndof, numberOfHarmonics)
numberOfSpatialUnknowns = ndof*numberOfHarmonics;
topBorder = borderedMatrix(1:numberOfSpatialUnknowns, end);
bottomBorder = borderedMatrix(end, 1:numberOfSpatialUnknowns);
borderResponse = apply_temporal_spatial_inverse( ...
    topBorder, factors, ndof, numberOfHarmonics);
borderSchur = bottomBorder*borderResponse;
schurScale = max(norm(bottomBorder)*norm(borderResponse), eps);
if ~isfinite(real(borderSchur)) || ~isfinite(imag(borderSchur)) || ...
        abs(borderSchur) <= 1.0e-12*schurScale
    error('wnl_compute_mode:BorderedPreconditionerSchurComplement', ...
        ['The regularized block-Jacobi bordered Schur complement is ', ...
         'zero, nonfinite, or numerically unresolved (|S|=%.3e, ', ...
         'scale=%.3e).'], abs(borderSchur), schurScale);
end
end

function result = apply_bordered_block_jacobi_inverse( ...
        rightHandSide, factors, ndof, numberOfHarmonics, ...
        bottomBorder, borderResponse, borderSchur)
numberOfSpatialUnknowns = ndof*numberOfHarmonics;
spatialRightHandSide = rightHandSide(1:numberOfSpatialUnknowns);
scalarRightHandSide = rightHandSide(end);
unborderedSolution = apply_temporal_spatial_inverse( ...
    spatialRightHandSide, factors, ndof, numberOfHarmonics);

% Invert [D c; p' 0] by its scalar Schur complement.  With
% z=D\f, v=D\c and S=p'*v,
%   alpha=(p'*z-g)/S,  x=z-v*alpha.
borderMultiplier = ...
    (bottomBorder*unborderedSolution-scalarRightHandSide)/borderSchur;
spatialSolution = unborderedSolution-borderResponse*borderMultiplier;
result = [spatialSolution; borderMultiplier];
if any(~isfinite(real(result))) || any(~isfinite(imag(result)))
    error('wnl_compute_mode:BlockPreconditionerNonfinite', ...
        ['The regularized bordered block-Jacobi inverse returned a ', ...
         'nonfinite value.']);
end
end

function result = apply_temporal_spatial_inverse( ...
        rightHandSide, factors, ndof, numberOfHarmonics)
numberOfSpatialUnknowns = ndof*numberOfHarmonics;
if size(rightHandSide, 1) ~= numberOfSpatialUnknowns
    error('wnl_compute_mode:BlockPreconditionerSize', ...
        ['The temporal spatial inverse received %d rows; expected %d.'], ...
        size(rightHandSide, 1), numberOfSpatialUnknowns);
end
result = complex(zeros(size(rightHandSide)));
for harmonicIndex = 1:numberOfHarmonics
    indices = (harmonicIndex-1)*ndof+(1:ndof);
    result(indices, :) = factors{harmonicIndex}\rightHandSide(indices, :);
end
if any(~isfinite(real(result))) || any(~isfinite(imag(result)))
    error('wnl_compute_mode:BlockPreconditionerNonfinite', ...
        'The regularized temporal-block inverse returned a nonfinite value.');
end
end

function [sigma, scaledResidual, constraintResidual, valid] = ...
        adjoint_candidate_metrics(A, Bslow, left, borderMultiplier, ...
        pairingUnit, targetResidual, constraintTolerance, nullTolerance)
finiteLeft = all(isfinite(real(left))) && all(isfinite(imag(left)));
finiteBorder = isfinite(real(borderMultiplier)) && ...
    isfinite(imag(borderMultiplier));
leftNorm = norm(left);
if ~finiteLeft || ~finiteBorder || ...
        ~isfinite(leftNorm) || leftNorm <= nullTolerance
    sigma = Inf;
    scaledResidual = Inf;
    constraintResidual = Inf;
    valid = false;
    return;
end
[scaledResidual,residualDetails] = wnl_descriptor_residual( ...
    A,Bslow,left,'adjoint');
sigma = residualDetails.effectiveResidual;
constraintResidual = abs(pairingUnit'*left-1);
valid = isfinite(sigma) && isfinite(scaledResidual) && ...
    isfinite(constraintResidual) && ...
    scaledResidual <= targetResidual && ...
    constraintResidual <= constraintTolerance;
end

function count = gmres_iteration_count(iteration, restart)
if isempty(iteration)
    count = 0;
elseif isscalar(iteration)
    count = iteration;
else
    % MATLAB reports [outer inner]. The current outer cycle has completed
    % only `inner` steps, whereas each preceding cycle completed `restart`.
    count = max(iteration(1)-1, 0)*restart+iteration(2);
end
end

function [vector, sigma, information] = ...
        tracked_constrained_null(block, seed, opts)
%TRACKED_CONSTRAINED_NULL Reconstruct a physical null direction.
%
% A primitive incompressible discretization can contain pressure, gauge,
% or constraint singular directions with exactly zero interface motion.
% Ranking a finite number of global singular vectors therefore does not
% reliably locate an interfacial mode.  Instead solve
%
%   min_q ||A_s q||^2 + w^2 |c'*q-1|^2 + alpha ||q||^2,
%
% where A_s is A scaled by its operator norm and c is the requested
% interface/Floquet seed.  Directions with c'*q=0 cannot satisfy the
% branch constraint.  All bulk, wall, interface, pressure, volume, and
% contact-line rows remain in A_s and are solved simultaneously.

A = block.A;
Bslow = block.Bslow;

if numel(seed) ~= size(A, 2)
    error('wnl_compute_mode:DirectSeedSize', ...
        'Mode-tracking seed has %d entries; the operator requires %d.', ...
        numel(seed), size(A, 2));
end
seed = seed(:);
seedNorm = norm(seed);
if seedNorm <= eps
    error('wnl_compute_mode:ZeroDirectSeed', ...
        'The mode-tracking seed is zero.');
end
seed = seed/seedNorm;

validateattributes(opts.modeTrackingConstraintWeight, {'numeric'}, ...
    {'scalar', 'real', 'positive', 'finite'});
validateattributes(opts.modeTrackingRegularization, {'numeric'}, ...
    {'scalar', 'real', 'nonnegative', 'finite'});
validateattributes(opts.modeTrackingSolveTolerance, {'numeric'}, ...
    {'scalar', 'real', 'positive', 'finite'});
validateattributes(opts.modeTrackingMaxIterations, {'numeric'}, ...
    {'scalar', 'real', 'integer', 'positive'});

[equilibratedA, rowScale] = equilibrate_rows(A);
numberOfUnknowns = size(A, 2);
weight = opts.modeTrackingConstraintWeight;
regularization = opts.modeTrackingRegularization;
augmentedA = [equilibratedA; weight*seed'; ...
    sqrt(regularization)*speye(numberOfUnknowns)];
augmentedRightHandSide = [zeros(size(A, 1), 1); weight; ...
    zeros(numberOfUnknowns, 1)];
[augmentedA, columnScale] = equilibrate_columns(augmentedA);

[scaledVector, flag, relativeResidual, iterations] = lsqr( ...
    augmentedA, augmentedRightHandSide, ...
    opts.modeTrackingSolveTolerance, opts.modeTrackingMaxIterations);
vector = columnScale.*scaledVector;
constraintBeforeNormalization = seed'*vector;
if abs(constraintBeforeNormalization) < ...
        opts.modeTrackingMinimumConstraint
    error('wnl_compute_mode:ConstrainedModeTrackingFailed', ...
        ['The full residual reconstruction could not create a mode with ', ...
         'nonzero interface-seed projection. Verify m, radialIndex, s, ', ...
         'N, and the contact-line condition. LSQR flag=%d, relres=%.3e.'], ...
        flag, relativeResidual);
end
vector = vector/constraintBeforeNormalization;

[scaledResidual,residualDetails] = wnl_descriptor_residual( ...
    A,Bslow,vector,'direct');
sigma = residualDetails.effectiveResidual;
operatorScale = residualDetails.operatorScale;
information = struct();
information.method = 'interface-constrained full residual';
information.operatorScale = operatorScale;
information.effectiveSingularValue = sigma;
information.scaledResidual = scaledResidual;
information.constraintBeforeNormalization = ...
    constraintBeforeNormalization;
information.constraintAfterNormalization = seed'*vector;
information.constraintWeight = weight;
information.regularization = regularization;
information.flag = flag;
information.relativeResidual = relativeResidual;
information.iterations = iterations;
information.restarts = 0;
information.numberOfAttempts = 1;
information.selectedAttempt = 1;
information.rowScaleRange = positive_range(rowScale);
information.columnScaleRange = positive_range(columnScale);
information.residualDetails = residualDetails;

if flag ~= 0 && opts.verbose
    warning('wnl_compute_mode:ConstrainedSolveNotConverged', ...
        ['The interface-constrained LSQR solve returned flag %d after ', ...
         '%d iterations (relres %.3e). Check the reported full-state ', ...
         'residual before using nonlinear coefficients.'], ...
        flag, iterations, relativeResidual);
end
end

function [vector, sigma, information] = ...
        reconstruct_from_prescribed_dofs(block, seed, spec, opts)
%RECONSTRUCT_FROM_PRESCRIBED_DOFS Lift a reduced interface null vector.
%
% For a free-contact-line Bessel branch, the reduced linear calculation
% already supplies every zeta(r,n).  Hold those interface coefficients
% fixed and solve every row of the full primitive operator for both-layer
% velocity and pressure.  This is the residual-consistent reconstruction
% of the Schur-complement interface mode.

A = block.A;
Bslow = block.Bslow;

localDofs = unique(spec.prescribedDofs(:));
if any(localDofs < 1) || any(localDofs > spec.ndof) || ...
        any(localDofs ~= round(localDofs))
    error('wnl_compute_mode:PrescribedDofs', ...
        'spec.prescribedDofs must contain valid local integer indices.');
end
numberOfHarmonics = numel(spec.n);
offsets = (0:numberOfHarmonics-1)*spec.ndof;
prescribed = reshape(localDofs+offsets, [], 1);
if numel(seed) ~= size(A, 2)
    error('wnl_compute_mode:DirectSeedSize', ...
        'Mode seed has %d entries; the operator requires %d.', ...
        numel(seed), size(A, 2));
end
prescribedValues = seed(prescribed);
if norm(prescribedValues) <= eps
    error('wnl_compute_mode:ZeroPrescribedSeed', ...
        'The prescribed interface portion of the mode seed is zero.');
end
prescribedValues = prescribedValues/norm(prescribedValues);

isFree = true(size(A, 2), 1);
isFree(prescribed) = false;
freeDofs = find(isFree);
reconstructionA = A(:, freeDofs);
reconstructionRightHandSide = ...
    -A(:, prescribed)*prescribedValues;
[scaledA, scaledRightHandSide, rowScale] = ...
    equilibrate_equations(reconstructionA, ...
    reconstructionRightHandSide);

regularization = opts.modeTrackingRegularization;
numberOfFreeDofs = numel(freeDofs);
augmentedA = [scaledA; ...
    sqrt(regularization)*speye(numberOfFreeDofs)];
augmentedRightHandSide = [scaledRightHandSide; ...
    zeros(numberOfFreeDofs, 1)];
[augmentedA, columnScale] = equilibrate_columns(augmentedA);
validateattributes(opts.directLiftMaxRestarts, {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative'});
validateattributes(opts.directLiftSeedResidualTolerance,{'numeric'}, ...
    {'scalar','real','positive','finite'});
scaledFreeValues = complex(zeros(numberOfFreeDofs, 1));
warmStartUsed = false;
warmStartResidual = NaN;
warmStartSigma = Inf;
warmStartResidualDetails = struct();
if isfield(spec,'directLiftInitialVector') && ...
        ~isempty(spec.directLiftInitialVector)
    warmVector = spec.directLiftInitialVector(:);
    if numel(warmVector) ~= size(A,2) || ...
            any(~isfinite(real(warmVector))) || ...
            any(~isfinite(imag(warmVector)))
        error('wnl_compute_mode:DirectLiftWarmStart', ...
            ['The recovery warm-start vector must be finite and have ', ...
             'the same length as the full Floquet state.']);
    end
    warmPrescribed = warmVector(prescribed);
    warmDenominator = warmPrescribed'*warmPrescribed;
    if isfinite(real(warmDenominator)) && ...
            isfinite(imag(warmDenominator)) && ...
            abs(warmDenominator) > eps
        % Align the cached state to the current reduced-interface phase and
        % scale, then impose the current prescribed values exactly.
        warmScale = (warmPrescribed'*prescribedValues)/warmDenominator;
        warmVector = warmScale*warmVector;
        warmVector(prescribed) = prescribedValues;
        scaledFreeValues = warmVector(freeDofs)./columnScale;
        warmStartUsed = true;
        [warmStartResidual,warmStartResidualDetails] = ...
            wnl_descriptor_residual(A,Bslow,warmVector,'direct');
        warmStartSigma = warmStartResidualDetails.effectiveResidual;
    end
end
maximumAttempts = opts.directLiftMaxRestarts+1;
attemptFlags = nan(maximumAttempts, 1);
attemptRelativeResiduals = nan(maximumAttempts, 1);
attemptIterations = nan(maximumAttempts, 1);
attemptCumulativeIterations = nan(maximumAttempts, 1);
attemptEffectiveSingularValues = nan(maximumAttempts, 1);
attemptScaledResiduals = nan(maximumAttempts, 1);
attemptPhysicalStateNorms = nan(maximumAttempts, 1);
attemptFullStateNorms = nan(maximumAttempts, 1);
attemptAlgebraicInflationFactors = nan(maximumAttempts, 1);
bestScaledResidual = Inf;
bestEffectiveSingularValue = Inf;
bestVector = [];
bestFlag = NaN;
bestRelativeResidual = NaN;
bestAttemptIndex = NaN;
if warmStartUsed
    bestScaledResidual = warmStartResidual;
    bestEffectiveSingularValue = warmStartSigma;
    bestVector = warmVector;
    bestAttemptIndex = 0;
end
totalIterations = 0;
numberOfAttempts = 0;
liftResidualTarget = opts.modeResidualTolerance;
if opts.refineOperatingPointEigenpair && ...
        abs(wnl_spec_lambda(spec)) > 1.0e-13
    liftResidualTarget = max(liftResidualTarget, ...
        opts.directLiftSeedResidualTolerance);
end

for attemptIndex = 1:maximumAttempts
    [candidate, flag, relativeResidual, iterationsThisAttempt] = lsqr( ...
        augmentedA, augmentedRightHandSide, ...
        opts.modeTrackingSolveTolerance, ...
        opts.modeTrackingMaxIterations, [], [], scaledFreeValues);
    numberOfAttempts = attemptIndex;
    totalIterations = totalIterations+iterationsThisAttempt;

    candidateVector = complex(zeros(size(A, 2), 1));
    candidateVector(prescribed) = prescribedValues;
    candidateVector(freeDofs) = columnScale.*candidate;
    [candidateScaledResidual,candidateResidualDetails] = ...
        wnl_descriptor_residual(A,Bslow,candidateVector,'direct');
    candidateSigma = candidateResidualDetails.effectiveResidual;
    operatorScale = candidateResidualDetails.operatorScale;

    attemptFlags(attemptIndex) = flag;
    attemptRelativeResiduals(attemptIndex) = relativeResidual;
    attemptIterations(attemptIndex) = iterationsThisAttempt;
    attemptCumulativeIterations(attemptIndex) = totalIterations;
    attemptEffectiveSingularValues(attemptIndex) = candidateSigma;
    attemptScaledResiduals(attemptIndex) = candidateScaledResidual;
    attemptPhysicalStateNorms(attemptIndex) = ...
        candidateResidualDetails.physicalVectorNorm;
    attemptFullStateNorms(attemptIndex) = ...
        candidateResidualDetails.fullVectorNorm;
    attemptAlgebraicInflationFactors(attemptIndex) = ...
        candidateResidualDetails.fullToPhysicalNormRatio;

    % LSQR minimizes the equilibrated, regularized augmented equations.
    % That objective need not decrease the physical residual ||A*q|| used
    % by the WNL convergence gate. Checkpoint the best physical candidate
    % so a later restart cannot replace a more neutral reconstructed mode
    % by a worse augmented least-squares iterate.
    if isempty(bestVector) || (isfinite(candidateScaledResidual) && ...
            (~isfinite(bestScaledResidual) || ...
            candidateScaledResidual < bestScaledResidual))
        bestScaledResidual = candidateScaledResidual;
        bestEffectiveSingularValue = candidateSigma;
        bestVector = candidateVector;
        bestFlag = flag;
        bestRelativeResidual = relativeResidual;
        bestAttemptIndex = attemptIndex;
    end

    scaledFreeValues = candidate;
    if candidateScaledResidual <= liftResidualTarget || flag == 0
        break;
    end
end

attemptFlags = attemptFlags(1:numberOfAttempts);
attemptRelativeResiduals = ...
    attemptRelativeResiduals(1:numberOfAttempts);
attemptIterations = attemptIterations(1:numberOfAttempts);
attemptCumulativeIterations = ...
    attemptCumulativeIterations(1:numberOfAttempts);
attemptEffectiveSingularValues = ...
    attemptEffectiveSingularValues(1:numberOfAttempts);
attemptScaledResiduals = attemptScaledResiduals(1:numberOfAttempts);
attemptPhysicalStateNorms = ...
    attemptPhysicalStateNorms(1:numberOfAttempts);
attemptFullStateNorms = attemptFullStateNorms(1:numberOfAttempts);
attemptAlgebraicInflationFactors = ...
    attemptAlgebraicInflationFactors(1:numberOfAttempts);

vector = bestVector;
sigma = bestEffectiveSingularValue;
scaledResidual = bestScaledResidual;
restarts = numberOfAttempts-1;
[~,selectedResidualDetails] = wnl_descriptor_residual( ...
    A,Bslow,vector,'direct');

information = struct();
information.method = 'prescribed-interface full-state lift';
information.operatorScale = operatorScale;
information.effectiveSingularValue = sigma;
information.scaledResidual = scaledResidual;
information.flag = bestFlag;
information.relativeResidual = bestRelativeResidual;
information.iterations = totalIterations;
information.restarts = restarts;
information.numberOfAttempts = numberOfAttempts;
information.selectedAttempt = bestAttemptIndex;
information.selectedAttemptIndex = bestAttemptIndex;
if bestAttemptIndex == 0
    information.selectedCumulativeIterations = 0;
else
    information.selectedCumulativeIterations = ...
        attemptCumulativeIterations(bestAttemptIndex);
end
information.lastFlag = attemptFlags(end);
information.lastRelativeResidual = attemptRelativeResiduals(end);
information.attemptFlags = attemptFlags;
information.attemptRelativeResiduals = attemptRelativeResiduals;
information.attemptIterations = attemptIterations;
information.attemptCumulativeIterations = attemptCumulativeIterations;
information.attemptEffectiveSingularValues = ...
    attemptEffectiveSingularValues;
information.attemptScaledResiduals = attemptScaledResiduals;
information.attemptPhysicalStateNorms = attemptPhysicalStateNorms;
information.attemptFullStateNorms = attemptFullStateNorms;
information.attemptAlgebraicInflationFactors = ...
    attemptAlgebraicInflationFactors;
information.numberOfPrescribedDofs = numel(prescribed);
information.seedResidualTolerance = liftResidualTarget;
information.finalLinearResidualTolerance = opts.modeResidualTolerance;
information.acceptedAsRefinementSeed = scaledResidual <= ...
    liftResidualTarget && scaledResidual > opts.modeResidualTolerance;
information.rowScaleRange = positive_range(rowScale);
information.columnScaleRange = positive_range(columnScale);
information.residualDetails = selectedResidualDetails;
information.warmStartUsed = warmStartUsed;
information.warmStartResidual = warmStartResidual;
information.selectedFromWarmStart = bestAttemptIndex == 0;
information.warmStartResidualDetails = warmStartResidualDetails;
if isfield(spec,'recoveryWarmStartFile')
    information.warmStartFile = spec.recoveryWarmStartFile;
else
    information.warmStartFile = '';
end

if (~isfinite(scaledResidual) || ...
        scaledResidual > liftResidualTarget) && opts.verbose
    warning('wnl_compute_mode:InterfaceLiftNotConverged', ...
        ['The best prescribed-interface LSQR candidate has physical ', ...
         'scaled residual %.3e after %d total iterations and %d ', ...
         'restarts; the required tolerance is %.3e. Attempt %d of %d ', ...
         'was retained (selected flag %d, last flag %d). The final mode ', ...
         'residual gates will prevent nonlinear coefficients if ', ...
         'the subsequent full-eigenpair correction remains inaccurate.'], ...
        scaledResidual, totalIterations, restarts, ...
        liftResidualTarget, bestAttemptIndex, ...
        numberOfAttempts, bestFlag, attemptFlags(end));
elseif information.acceptedAsRefinementSeed && opts.verbose
    fprintf(['WNL prescribed-interface lift accepted as a Newton seed: ', ...
        'residual %.3e <= seed tolerance %.3e. Final linear/coefficient ', ...
        'gates remain %.3e/%.3e.\n'],scaledResidual, ...
        liftResidualTarget,opts.modeResidualTolerance, ...
        opts.coefficientModeResidualTolerance);
end
end

function [scaledA, rowScale] = equilibrate_rows(A)
[scaledA, ~, rowScale] = equilibrate_equations( ...
    A, complex(zeros(size(A, 1), 1)));
end

function [scaledA, scaledB, rowScale] = equilibrate_equations(A, b)
rowNorm = sqrt(full(sum(abs(A).^2, 2)));
largest = max(rowNorm);
if isempty(largest) || largest <= eps
    rowScale = ones(size(rowNorm));
else
    floorValue = max(largest*1.0e-12, eps);
    rowScale = ones(size(rowNorm));
    positive = rowNorm > 0;
    rowScale(positive) = 1./max(rowNorm(positive), floorValue);
end
scaledA = spdiags(rowScale, 0, size(A, 1), size(A, 1))*A;
scaledB = rowScale.*b;
end

function [scaledA, columnScale] = equilibrate_columns(A)
columnNorm = sqrt(full(sum(abs(A).^2, 1))).';
largest = max(columnNorm);
if isempty(largest) || largest <= eps
    columnScale = ones(size(columnNorm));
else
    floorValue = max(largest*1.0e-12, eps);
    columnScale = 1./max(columnNorm, floorValue);
end
scaledA = A*spdiags(columnScale, 0, size(A, 2), size(A, 2));
end

function scale = deterministic_matrix_scale(A)
% Upper bound for ||A||_2 without an iterative norm estimate.
oneNorm = norm(A, 1);
infinityNorm = norm(A, inf);
scale = max(sqrt(max(oneNorm, 0)*max(infinityNorm, 0)), eps);
end

function range = positive_range(values)
positive = values(isfinite(values) & values > 0);
if isempty(positive)
    range = [NaN, NaN];
else
    range = [min(positive), max(positive)];
end
end

function validate_block(block, spec)
required = {'A', 'Bslow'};
for j = 1:numel(required)
    if ~isfield(block, required{j})
        error('wnl_compute_mode:MissingBlockField', ...
            'model.block(%s) did not return block.%s.', ...
            spec.label, required{j});
    end
end
n = spec.ndof * numel(spec.n);
if ~isequal(size(block.A), [n, n])
    error('wnl_compute_mode:BadA', ...
        'block.A must have size [%d,%d].', n, n);
end
if ~isequal(size(block.Bslow), [n, n])
    error('wnl_compute_mode:BadBslow', ...
        'block.Bslow must have size [%d,%d].', n, n);
end
end

function [u, sigma, v] = smallest_svd(A, opts)
n = max(size(A));
if n <= opts.fullSvdMax
    [uAll, sAll, vAll] = svd(full(A), 'econ');
    singularValues = diag(sAll);
    [sigma, idx] = min(singularValues);
    u = uAll(:, idx);
    v = vAll(:, idx);
    return;
end

try
    [u, s, v] = svds(A, 1, 'smallest');
    sigma = s(1, 1);
catch
    [u, s, v] = svds(A, 1, 0);
    sigma = s(1, 1);
end
end
