function summary = vi_package_60hz_coefficients()
%VI_PACKAGE_60HZ_COEFFICIENTS Save a compact audited 60 Hz coefficient set.

root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
axisFile = fullfile(root, ...
    'vi_wnl_complete_ag0-4_fHz-60_modes-m0l9-m0l2_Nr16.mat');
m2File = fullfile(root, ...
    ['vi_wnl_complete_ag0-4_fHz-60_modes-m2l9-m2l2_', ...
     'chebyshev_Nr36.mat']);
m2LowerFile = fullfile(root, ...
    ['vi_wnl_complete_ag0-4_fHz-60_modes-m2l9-m2l2_', ...
     'chebyshev_Nr32.mat']);
m2UpperFile = fullfile(root, ...
    ['vi_wnl_selfaudit_ag0-4_fHz-60_mode-m2l9_', ...
     'chebyshev_Nr40.mat']);
required = {axisFile,m2File,m2LowerFile,m2UpperFile};
for fileIndex = 1:numel(required)
    if ~isfile(required{fileIndex})
        error('vi_package_60hz_coefficients:MissingFile', ...
            'Required coefficient audit file is missing: %s', ...
            required{fileIndex});
    end
end

axisSaved = load(axisFile,'output');
m2Saved = load(m2File,'output');
m2LowerSaved = load(m2LowerFile,'output');
m2UpperSaved = load(m2UpperFile,'output');
axisCase = case_record(axisSaved.output,axisFile);
m2Case = case_record(m2Saved.output,m2File);

lowerWnl = m2LowerSaved.output.weaklyNonlinear;
upperWnl = m2UpperSaved.output.weaklyNonlinear;
m2Case.radialConvergence = struct( ...
    'g11Nr36',m2Case.GInternal(1,1), ...
    'g11Nr40',upperWnl.g(1,1), ...
    'g11RelativeChange36To40',relative_change( ...
        m2Case.GInternal(1,1),upperWnl.g(1,1)), ...
    'g22Nr32',lowerWnl.g(2,2), ...
    'g22Nr36',m2Case.GInternal(2,2), ...
    'g22RelativeChange32To36',relative_change( ...
        lowerWnl.g(2,2),m2Case.GInternal(2,2)), ...
    'crossCoefficientSecondGridAvailable',false, ...
    'note',['Self coefficients have independent radial checks. ', ...
        'Cross coefficients pass every local discrete gate on Nr=36, ', ...
        'but have not been repeated on a second radial grid.']);
axisCase.radialConvergence = struct( ...
    'crossCoefficientSecondGridAvailable',false, ...
    'note',['The Bessel-enriched Nr=16 result passes every local ', ...
        'discrete gate; an independent radial-grid comparison was not ', ...
        'performed.']);

summary = struct();
summary.schemaVersion = 'V2-60Hz-complete-cubic-radial-audit';
summary.frequencyHz = 60;
summary.accelerationOverG = 4;
summary.amplitudeConvention = ...
    'physical peak interface displacement zeta/h';
summary.amplitudeEquation = m2Saved.output.weaklyNonlinear. ...
    amplitudeEquation;
summary.certificationScope = [ ...
    'All local discrete mode, forced-field, scaling, and coefficient ', ...
    'gates pass. The m=2 self terms include radial convergence checks; ', ...
    'cross-term and axisymmetric second-grid checks remain separate.'];
summary.cases = {axisCase;m2Case};
summaryFile = fullfile(root, ...
    'vi_wnl_complete_60Hz_ag0-4_coefficients.mat');
save(summaryFile,'summary','-v7');
fprintf('Saved %s\n',summaryFile);
end

function record = case_record(output,sourceFile)
wnl = output.weaklyNonlinear;
assert(wnl.requestedCoefficientValidity && ...
    wnl.fullCoefficientMatrixComputed && ...
    all(wnl.forcedSolvesValid,'all') && ...
    all(wnl.validCubicScaling,'all') && ...
    wnl.numericalCoefficientValidity, ...
    'The source case does not pass every local coefficient gate.');
record = struct();
record.label = strjoin(cellfun(@(mode) mode.spec.label, ...
    wnl.modes,'UniformOutput',false),' + ');
record.modeLabels = cellfun(@(mode) mode.spec.label, ...
    wnl.modes,'UniformOutput',false);
record.coordinateTypes = wnl.coordinateTypes;
record.sourceFile = sourceFile;
record.codeRelease = output.codeRelease;
record.coefficientConventionVersion = ...
    wnl.coefficientConventionVersion;
record.amplitudeScalesToPeakZetaOverH = ...
    wnl.amplitudeScalesToPeakZetaOverH;
record.lambda = wnl.linearCoefficients;
record.mu = wnl.mu;
record.GInternal = wnl.g;
record.GPhysicalPeak = wnl.gPhysicalPeak;
record.HInternal = wnl.phaseSensitiveG;
record.HPhysicalPeak = wnl.phaseSensitiveGPhysicalPeak;
record.radialGridType = output.operatorMetadata.radialGrid.typeUsed;
record.Nr = output.operatorMetadata.radialGrid.numberOfPoints;
record.modeDirectResiduals = cellfun( ...
    @(mode) mode.directResidual,wnl.modes);
record.modeAdjointResiduals = cellfun( ...
    @(mode) mode.leftResidual,wnl.modes);
record.forcedFieldResiduals = forced_field_residuals(wnl);
record.maximumForcedFieldResidual = max(record.forcedFieldResiduals);
record.forcedSolvesValid = all(wnl.forcedSolvesValid,'all');
record.validCubicScaling = all(wnl.validCubicScaling,'all');
record.fullCoefficientMatrixComputed = ...
    wnl.fullCoefficientMatrixComputed;
record.numericalCoefficientValidity = ...
    wnl.numericalCoefficientValidity;
record.slowEnvelopeValid = wnl.slowEnvelopeValid;
end

function residuals = forced_field_residuals(wnl)
residuals = [];
for modeIndex = 1:numel(wnl.self)
    residuals = append_solution_residual( ...
        residuals,wnl.self{modeIndex}.qAA);
    residuals = append_solution_residual( ...
        residuals,wnl.self{modeIndex}.qAbarA);
end
for targetIndex = 1:size(wnl.cross,1)
    for sourceIndex = 1:size(wnl.cross,2)
        crossResult = wnl.cross{targetIndex,sourceIndex};
        if ~isstruct(crossResult)
            continue;
        end
        residuals = append_solution_residual( ...
            residuals,crossResult.qAbarB);
        residuals = append_solution_residual( ...
            residuals,crossResult.qAB);
    end
end
end

function residuals = append_solution_residual(residuals,solution)
if isstruct(solution) && ...
        isfield(solution,'acceptanceRelativeEquationResidual')
    residuals(end+1) = solution.acceptanceRelativeEquationResidual; %#ok<AGROW>
end
end

function value = relative_change(reference,candidate)
value = abs(candidate-reference)/max(abs(candidate),eps);
end
